// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->
    typedef struct rfnoc_axis {
        ap_int<32> data;
        ap_uint<1> last;
       } rfnoc_axis;



// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "i_data_data_V"
#define AUTOTB_TVIN_i_data_data_V  "../tv/cdatafile/c.correlateTop.autotvin_i_data_data_V.dat"
// wrapc file define: "i_data_last_V"
#define AUTOTB_TVIN_i_data_last_V  "../tv/cdatafile/c.correlateTop.autotvin_i_data_last_V.dat"
// wrapc file define: "o_data_data_V"
#define AUTOTB_TVOUT_o_data_data_V  "../tv/cdatafile/c.correlateTop.autotvout_o_data_data_V.dat"
#define AUTOTB_TVIN_o_data_data_V  "../tv/cdatafile/c.correlateTop.autotvin_o_data_data_V.dat"
// wrapc file define: "o_data_last_V"
#define AUTOTB_TVOUT_o_data_last_V  "../tv/cdatafile/c.correlateTop.autotvout_o_data_last_V.dat"
#define AUTOTB_TVIN_o_data_last_V  "../tv/cdatafile/c.correlateTop.autotvin_o_data_last_V.dat"
// wrapc file define: "start_V"
#define AUTOTB_TVIN_start_V  "../tv/cdatafile/c.correlateTop.autotvin_start_V.dat"
// wrapc file define: "phaseClass_V"
#define AUTOTB_TVIN_phaseClass_V  "../tv/cdatafile/c.correlateTop.autotvin_phaseClass_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "o_data_data_V"
#define AUTOTB_TVOUT_PC_o_data_data_V  "../tv/rtldatafile/rtl.correlateTop.autotvout_o_data_data_V.dat"
// tvout file define: "o_data_last_V"
#define AUTOTB_TVOUT_PC_o_data_last_V  "../tv/rtldatafile/rtl.correlateTop.autotvout_o_data_last_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			i_data_data_V_depth = 0;
			i_data_last_V_depth = 0;
			o_data_data_V_depth = 0;
			o_data_last_V_depth = 0;
			start_V_depth = 0;
			phaseClass_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{i_data_data_V " << i_data_data_V_depth << "}\n";
			total_list << "{i_data_last_V " << i_data_last_V_depth << "}\n";
			total_list << "{o_data_data_V " << o_data_data_V_depth << "}\n";
			total_list << "{o_data_last_V " << o_data_last_V_depth << "}\n";
			total_list << "{start_V " << start_V_depth << "}\n";
			total_list << "{phaseClass_V " << phaseClass_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int i_data_data_V_depth;
		int i_data_last_V_depth;
		int o_data_data_V_depth;
		int o_data_last_V_depth;
		int start_V_depth;
		int phaseClass_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void correlateTop (
rfnoc_axis* i_data,
rfnoc_axis* o_data,
ap_uint<1> start,
ap_uint<4> phaseClass);

void AESL_WRAP_correlateTop (
rfnoc_axis* i_data,
rfnoc_axis* o_data,
ap_uint<1> start,
ap_uint<4> phaseClass)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "o_data_data_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_o_data_data_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_o_data_data_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_o_data_data_V, AESL_token); // data

			sc_bv<32> *o_data_data_V_pc_buffer = new sc_bv<32>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'o_data_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'o_data_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					o_data_data_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_o_data_data_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_o_data_data_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: o_data_data_V
				{
					// bitslice(31, 0)
					// {
						// celement: o_data.data.V(31, 0)
						// {
							sc_lv<32>* o_data_data_V_lv0_0_0_1 = new sc_lv<32>[1];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: o_data.data.V(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(o_data[0].data) != NULL) // check the null address if the c port is array or others
								{
									o_data_data_V_lv0_0_0_1[hls_map_index].range(31, 0) = sc_bv<32>(o_data_data_V_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: o_data.data.V(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : o_data[i_0].data
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : o_data[0].data
								// output_left_conversion : o_data[i_0].data
								// output_type_conversion : (o_data_data_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(o_data[0].data) != NULL) // check the null address if the c port is array or others
								{
									o_data[i_0].data = (o_data_data_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] o_data_data_V_pc_buffer;
		}

		// output port post check: "o_data_last_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_o_data_last_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_o_data_last_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_o_data_last_V, AESL_token); // data

			sc_bv<1> *o_data_last_V_pc_buffer = new sc_bv<1>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'o_data_last_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'o_data_last_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					o_data_last_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_o_data_last_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_o_data_last_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: o_data_last_V
				{
					// bitslice(0, 0)
					// {
						// celement: o_data.last.V(0, 0)
						// {
							sc_lv<1>* o_data_last_V_lv0_0_0_1 = new sc_lv<1>[1];
						// }
					// }

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: o_data.last.V(0, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(o_data[0].last) != NULL) // check the null address if the c port is array or others
								{
									o_data_last_V_lv0_0_0_1[hls_map_index].range(0, 0) = sc_bv<1>(o_data_last_V_pc_buffer[hls_map_index].range(0, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: o_data.last.V(0, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : o_data[i_0].last
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : o_data[0].last
								// output_left_conversion : o_data[i_0].last
								// output_type_conversion : (o_data_last_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(o_data[0].last) != NULL) // check the null address if the c port is array or others
								{
									o_data[i_0].last = (o_data_last_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] o_data_last_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "i_data_data_V"
		char* tvin_i_data_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_i_data_data_V);

		// "i_data_last_V"
		char* tvin_i_data_last_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_i_data_last_V);

		// "o_data_data_V"
		char* tvin_o_data_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_o_data_data_V);
		char* tvout_o_data_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_o_data_data_V);

		// "o_data_last_V"
		char* tvin_o_data_last_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_o_data_last_V);
		char* tvout_o_data_last_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_o_data_last_V);

		// "start_V"
		char* tvin_start_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_start_V);

		// "phaseClass_V"
		char* tvin_phaseClass_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_phaseClass_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_i_data_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_i_data_data_V, tvin_i_data_data_V);

		sc_bv<32>* i_data_data_V_tvin_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: i_data_data_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: i_data.data.V(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : i_data[i_0].data
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : i_data[0].data
						// regulate_c_name       : i_data_data_V
						// input_type_conversion : (i_data[i_0].data).to_string(2).c_str()
						if (&(i_data[0].data) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> i_data_data_V_tmp_mem;
							i_data_data_V_tmp_mem = (i_data[i_0].data).to_string(2).c_str();
							i_data_data_V_tvin_wrapc_buffer[hls_map_index].range(31, 0) = i_data_data_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_i_data_data_V, "%s\n", (i_data_data_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_i_data_data_V, tvin_i_data_data_V);
		}

		tcl_file.set_num(1, &tcl_file.i_data_data_V_depth);
		sprintf(tvin_i_data_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_i_data_data_V, tvin_i_data_data_V);

		// release memory allocation
		delete [] i_data_data_V_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_i_data_last_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_i_data_last_V, tvin_i_data_last_V);

		sc_bv<1>* i_data_last_V_tvin_wrapc_buffer = new sc_bv<1>[1];

		// RTL Name: i_data_last_V
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: i_data.last.V(0, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : i_data[i_0].last
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : i_data[0].last
						// regulate_c_name       : i_data_last_V
						// input_type_conversion : (i_data[i_0].last).to_string(2).c_str()
						if (&(i_data[0].last) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> i_data_last_V_tmp_mem;
							i_data_last_V_tmp_mem = (i_data[i_0].last).to_string(2).c_str();
							i_data_last_V_tvin_wrapc_buffer[hls_map_index].range(0, 0) = i_data_last_V_tmp_mem.range(0, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_i_data_last_V, "%s\n", (i_data_last_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_i_data_last_V, tvin_i_data_last_V);
		}

		tcl_file.set_num(1, &tcl_file.i_data_last_V_depth);
		sprintf(tvin_i_data_last_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_i_data_last_V, tvin_i_data_last_V);

		// release memory allocation
		delete [] i_data_last_V_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_o_data_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_o_data_data_V, tvin_o_data_data_V);

		sc_bv<32>* o_data_data_V_tvin_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: o_data_data_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: o_data.data.V(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : o_data[i_0].data
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : o_data[0].data
						// regulate_c_name       : o_data_data_V
						// input_type_conversion : (o_data[i_0].data).to_string(2).c_str()
						if (&(o_data[0].data) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> o_data_data_V_tmp_mem;
							o_data_data_V_tmp_mem = (o_data[i_0].data).to_string(2).c_str();
							o_data_data_V_tvin_wrapc_buffer[hls_map_index].range(31, 0) = o_data_data_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_o_data_data_V, "%s\n", (o_data_data_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_o_data_data_V, tvin_o_data_data_V);
		}

		tcl_file.set_num(1, &tcl_file.o_data_data_V_depth);
		sprintf(tvin_o_data_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_o_data_data_V, tvin_o_data_data_V);

		// release memory allocation
		delete [] o_data_data_V_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_o_data_last_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_o_data_last_V, tvin_o_data_last_V);

		sc_bv<1>* o_data_last_V_tvin_wrapc_buffer = new sc_bv<1>[1];

		// RTL Name: o_data_last_V
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: o_data.last.V(0, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : o_data[i_0].last
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : o_data[0].last
						// regulate_c_name       : o_data_last_V
						// input_type_conversion : (o_data[i_0].last).to_string(2).c_str()
						if (&(o_data[0].last) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> o_data_last_V_tmp_mem;
							o_data_last_V_tmp_mem = (o_data[i_0].last).to_string(2).c_str();
							o_data_last_V_tvin_wrapc_buffer[hls_map_index].range(0, 0) = o_data_last_V_tmp_mem.range(0, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_o_data_last_V, "%s\n", (o_data_last_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_o_data_last_V, tvin_o_data_last_V);
		}

		tcl_file.set_num(1, &tcl_file.o_data_last_V_depth);
		sprintf(tvin_o_data_last_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_o_data_last_V, tvin_o_data_last_V);

		// release memory allocation
		delete [] o_data_last_V_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_start_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_start_V, tvin_start_V);

		sc_bv<1> start_V_tvin_wrapc_buffer;

		// RTL Name: start_V
		{
			// bitslice(0, 0)
			{
				// celement: start.V(0, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : start
						// sub_1st_elem          : 
						// ori_name_1st_elem     : start
						// regulate_c_name       : start_V
						// input_type_conversion : (start).to_string(2).c_str()
						if (&(start) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> start_V_tmp_mem;
							start_V_tmp_mem = (start).to_string(2).c_str();
							start_V_tvin_wrapc_buffer.range(0, 0) = start_V_tmp_mem.range(0, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_start_V, "%s\n", (start_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_start_V, tvin_start_V);
		}

		tcl_file.set_num(1, &tcl_file.start_V_depth);
		sprintf(tvin_start_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_start_V, tvin_start_V);

		// [[transaction]]
		sprintf(tvin_phaseClass_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_phaseClass_V, tvin_phaseClass_V);

		sc_bv<4> phaseClass_V_tvin_wrapc_buffer;

		// RTL Name: phaseClass_V
		{
			// bitslice(3, 0)
			{
				// celement: phaseClass.V(3, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : phaseClass
						// sub_1st_elem          : 
						// ori_name_1st_elem     : phaseClass
						// regulate_c_name       : phaseClass_V
						// input_type_conversion : (phaseClass).to_string(2).c_str()
						if (&(phaseClass) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<4> phaseClass_V_tmp_mem;
							phaseClass_V_tmp_mem = (phaseClass).to_string(2).c_str();
							phaseClass_V_tvin_wrapc_buffer.range(3, 0) = phaseClass_V_tmp_mem.range(3, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_phaseClass_V, "%s\n", (phaseClass_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_phaseClass_V, tvin_phaseClass_V);
		}

		tcl_file.set_num(1, &tcl_file.phaseClass_V_depth);
		sprintf(tvin_phaseClass_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_phaseClass_V, tvin_phaseClass_V);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		correlateTop(i_data, o_data, start, phaseClass);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_o_data_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_o_data_data_V, tvout_o_data_data_V);

		sc_bv<32>* o_data_data_V_tvout_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: o_data_data_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: o_data.data.V(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : o_data[i_0].data
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : o_data[0].data
						// regulate_c_name       : o_data_data_V
						// input_type_conversion : (o_data[i_0].data).to_string(2).c_str()
						if (&(o_data[0].data) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> o_data_data_V_tmp_mem;
							o_data_data_V_tmp_mem = (o_data[i_0].data).to_string(2).c_str();
							o_data_data_V_tvout_wrapc_buffer[hls_map_index].range(31, 0) = o_data_data_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_o_data_data_V, "%s\n", (o_data_data_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_o_data_data_V, tvout_o_data_data_V);
		}

		tcl_file.set_num(1, &tcl_file.o_data_data_V_depth);
		sprintf(tvout_o_data_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_o_data_data_V, tvout_o_data_data_V);

		// release memory allocation
		delete [] o_data_data_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_o_data_last_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_o_data_last_V, tvout_o_data_last_V);

		sc_bv<1>* o_data_last_V_tvout_wrapc_buffer = new sc_bv<1>[1];

		// RTL Name: o_data_last_V
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: o_data.last.V(0, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : o_data[i_0].last
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : o_data[0].last
						// regulate_c_name       : o_data_last_V
						// input_type_conversion : (o_data[i_0].last).to_string(2).c_str()
						if (&(o_data[0].last) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> o_data_last_V_tmp_mem;
							o_data_last_V_tmp_mem = (o_data[i_0].last).to_string(2).c_str();
							o_data_last_V_tvout_wrapc_buffer[hls_map_index].range(0, 0) = o_data_last_V_tmp_mem.range(0, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_o_data_last_V, "%s\n", (o_data_last_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_o_data_last_V, tvout_o_data_last_V);
		}

		tcl_file.set_num(1, &tcl_file.o_data_last_V_depth);
		sprintf(tvout_o_data_last_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_o_data_last_V, tvout_o_data_last_V);

		// release memory allocation
		delete [] o_data_last_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "i_data_data_V"
		delete [] tvin_i_data_data_V;
		// release memory allocation: "i_data_last_V"
		delete [] tvin_i_data_last_V;
		// release memory allocation: "o_data_data_V"
		delete [] tvout_o_data_data_V;
		delete [] tvin_o_data_data_V;
		// release memory allocation: "o_data_last_V"
		delete [] tvout_o_data_last_V;
		delete [] tvin_o_data_last_V;
		// release memory allocation: "start_V"
		delete [] tvin_start_V;
		// release memory allocation: "phaseClass_V"
		delete [] tvin_phaseClass_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

