// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matchFilter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matchFilter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matchFilter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> matchFilter::ap_ST_fsm_state1 = "1";
const sc_lv<10> matchFilter::ap_ST_fsm_state2 = "10";
const sc_lv<10> matchFilter::ap_ST_fsm_state3 = "100";
const sc_lv<10> matchFilter::ap_ST_fsm_state4 = "1000";
const sc_lv<10> matchFilter::ap_ST_fsm_state5 = "10000";
const sc_lv<10> matchFilter::ap_ST_fsm_state6 = "100000";
const sc_lv<10> matchFilter::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> matchFilter::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> matchFilter::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> matchFilter::ap_ST_fsm_state10 = "1000000000";
const sc_lv<1> matchFilter::ap_const_lv1_0 = "0";
const sc_lv<1> matchFilter::ap_const_lv1_1 = "1";
const sc_lv<2> matchFilter::ap_const_lv2_0 = "00";
const sc_lv<2> matchFilter::ap_const_lv2_2 = "10";
const sc_lv<2> matchFilter::ap_const_lv2_3 = "11";
const sc_lv<2> matchFilter::ap_const_lv2_1 = "1";
const sc_lv<32> matchFilter::ap_const_lv32_1 = "1";
const sc_lv<32> matchFilter::ap_const_lv32_5 = "101";
const sc_lv<32> matchFilter::ap_const_lv32_9 = "1001";
const sc_lv<32> matchFilter::ap_const_lv32_2 = "10";
const sc_lv<32> matchFilter::ap_const_lv32_3 = "11";
const bool matchFilter::ap_const_boolean_0 = false;
const sc_lv<32> matchFilter::ap_const_lv32_6 = "110";
const sc_lv<32> matchFilter::ap_const_lv32_8 = "1000";
const sc_lv<7> matchFilter::ap_const_lv7_7F = "1111111";
const sc_lv<32> matchFilter::ap_const_lv32_4 = "100";
const sc_lv<16> matchFilter::ap_const_lv16_0 = "0000000000000000";
const sc_lv<8> matchFilter::ap_const_lv8_0 = "00000000";
const sc_lv<64> matchFilter::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<7> matchFilter::ap_const_lv7_0 = "0000000";
const sc_lv<8> matchFilter::ap_const_lv8_80 = "10000000";
const sc_lv<8> matchFilter::ap_const_lv8_1 = "1";
const sc_lv<32> matchFilter::ap_const_lv32_10 = "10000";
const sc_lv<32> matchFilter::ap_const_lv32_1F = "11111";
const sc_lv<16> matchFilter::ap_const_lv16_FFFF = "1111111111111111";
const sc_lv<16> matchFilter::ap_const_lv16_FFFE = "1111111111111110";
const sc_lv<16> matchFilter::ap_const_lv16_FFFD = "1111111111111101";
const sc_lv<16> matchFilter::ap_const_lv16_FFFC = "1111111111111100";
const sc_lv<16> matchFilter::ap_const_lv16_1 = "1";
const sc_lv<16> matchFilter::ap_const_lv16_4 = "100";
const sc_lv<16> matchFilter::ap_const_lv16_7 = "111";
const sc_lv<16> matchFilter::ap_const_lv16_A = "1010";
const sc_lv<16> matchFilter::ap_const_lv16_D = "1101";
const sc_lv<16> matchFilter::ap_const_lv16_10 = "10000";
const sc_lv<16> matchFilter::ap_const_lv16_14 = "10100";
const sc_lv<16> matchFilter::ap_const_lv16_17 = "10111";
const sc_lv<16> matchFilter::ap_const_lv16_1A = "11010";
const sc_lv<16> matchFilter::ap_const_lv16_1C = "11100";
const sc_lv<16> matchFilter::ap_const_lv16_1E = "11110";
const sc_lv<16> matchFilter::ap_const_lv16_1F = "11111";
const sc_lv<16> matchFilter::ap_const_lv16_20 = "100000";
const sc_lv<5> matchFilter::ap_const_lv5_0 = "00000";
const sc_lv<32> matchFilter::ap_const_lv32_14 = "10100";
const bool matchFilter::ap_const_boolean_1 = true;

matchFilter::matchFilter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buffIn_data_V_U = new matchFilter_buffIbkb("buffIn_data_V_U");
    buffIn_data_V_U->clk(ap_clk);
    buffIn_data_V_U->reset(ap_rst_n_inv);
    buffIn_data_V_U->address0(buffIn_data_V_address0);
    buffIn_data_V_U->ce0(buffIn_data_V_ce0);
    buffIn_data_V_U->we0(buffIn_data_V_we0);
    buffIn_data_V_U->d0(buffIn_data_V_d0);
    buffIn_data_V_U->q0(buffIn_data_V_q0);
    buffIn_last_V_U = new matchFilter_buffIcud("buffIn_last_V_U");
    buffIn_last_V_U->clk(ap_clk);
    buffIn_last_V_U->reset(ap_rst_n_inv);
    buffIn_last_V_U->address0(buffIn_last_V_address0);
    buffIn_last_V_U->ce0(buffIn_last_V_ce0);
    buffIn_last_V_U->we0(buffIn_last_V_we0);
    buffIn_last_V_U->d0(buffIn_last_V_d0);
    buffIn_last_V_U->q0(buffIn_last_V_q0);
    matchFilter_mux_1dEe_U1 = new matchFilter_mux_1dEe<1,1,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,7,16>("matchFilter_mux_1dEe_U1");
    matchFilter_mux_1dEe_U1->din0(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din1(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din2(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din3(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din4(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din5(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din6(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din7(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din8(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din9(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din10(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din11(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din12(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din13(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din14(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din15(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din16(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din17(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din18(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din19(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din20(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din21(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din22(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din23(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din24(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din25(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din26(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din27(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din28(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din29(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din30(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din31(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din32(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din33(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din34(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din35(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din36(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din37(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din38(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din39(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din40(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din41(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din42(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din43(ap_var_for_const2);
    matchFilter_mux_1dEe_U1->din44(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din45(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din46(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din47(ap_var_for_const4);
    matchFilter_mux_1dEe_U1->din48(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din49(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din50(ap_var_for_const2);
    matchFilter_mux_1dEe_U1->din51(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din52(ap_var_for_const5);
    matchFilter_mux_1dEe_U1->din53(ap_var_for_const6);
    matchFilter_mux_1dEe_U1->din54(ap_var_for_const7);
    matchFilter_mux_1dEe_U1->din55(ap_var_for_const8);
    matchFilter_mux_1dEe_U1->din56(ap_var_for_const9);
    matchFilter_mux_1dEe_U1->din57(ap_var_for_const10);
    matchFilter_mux_1dEe_U1->din58(ap_var_for_const11);
    matchFilter_mux_1dEe_U1->din59(ap_var_for_const12);
    matchFilter_mux_1dEe_U1->din60(ap_var_for_const13);
    matchFilter_mux_1dEe_U1->din61(ap_var_for_const14);
    matchFilter_mux_1dEe_U1->din62(ap_var_for_const15);
    matchFilter_mux_1dEe_U1->din63(ap_var_for_const16);
    matchFilter_mux_1dEe_U1->din64(ap_var_for_const17);
    matchFilter_mux_1dEe_U1->din65(ap_var_for_const16);
    matchFilter_mux_1dEe_U1->din66(ap_var_for_const15);
    matchFilter_mux_1dEe_U1->din67(ap_var_for_const14);
    matchFilter_mux_1dEe_U1->din68(ap_var_for_const13);
    matchFilter_mux_1dEe_U1->din69(ap_var_for_const12);
    matchFilter_mux_1dEe_U1->din70(ap_var_for_const11);
    matchFilter_mux_1dEe_U1->din71(ap_var_for_const10);
    matchFilter_mux_1dEe_U1->din72(ap_var_for_const9);
    matchFilter_mux_1dEe_U1->din73(ap_var_for_const8);
    matchFilter_mux_1dEe_U1->din74(ap_var_for_const7);
    matchFilter_mux_1dEe_U1->din75(ap_var_for_const6);
    matchFilter_mux_1dEe_U1->din76(ap_var_for_const5);
    matchFilter_mux_1dEe_U1->din77(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din78(ap_var_for_const2);
    matchFilter_mux_1dEe_U1->din79(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din80(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din81(ap_var_for_const4);
    matchFilter_mux_1dEe_U1->din82(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din83(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din84(ap_var_for_const3);
    matchFilter_mux_1dEe_U1->din85(ap_var_for_const2);
    matchFilter_mux_1dEe_U1->din86(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din87(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din88(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din89(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din90(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din91(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din92(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din93(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din94(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din95(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din96(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din97(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din98(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din99(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din100(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din101(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din102(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din103(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din104(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din105(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din106(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din107(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din108(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din109(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din110(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din111(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din112(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din113(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din114(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din115(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din116(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din117(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din118(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din119(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din120(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din121(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din122(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din123(ap_var_for_const1);
    matchFilter_mux_1dEe_U1->din124(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din125(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din126(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din127(ap_var_for_const0);
    matchFilter_mux_1dEe_U1->din128(tmp_4_reg_693);
    matchFilter_mux_1dEe_U1->dout(merge_i_fu_316_p130);
    matchFilter_mac_meOg_U2 = new matchFilter_mac_meOg<1,3,16,16,21,21>("matchFilter_mac_meOg_U2");
    matchFilter_mac_meOg_U2->clk(ap_clk);
    matchFilter_mac_meOg_U2->reset(ap_rst_n_inv);
    matchFilter_mac_meOg_U2->din0(grp_fu_623_p0);
    matchFilter_mac_meOg_U2->din1(inI_V_fu_302_p4);
    matchFilter_mac_meOg_U2->din2(grp_fu_623_p2);
    matchFilter_mac_meOg_U2->ce(ap_var_for_const18);
    matchFilter_mac_meOg_U2->dout(grp_fu_623_p3);
    matchFilter_mac_meOg_U3 = new matchFilter_mac_meOg<1,3,16,16,21,21>("matchFilter_mac_meOg_U3");
    matchFilter_mac_meOg_U3->clk(ap_clk);
    matchFilter_mac_meOg_U3->reset(ap_rst_n_inv);
    matchFilter_mac_meOg_U3->din0(grp_fu_632_p0);
    matchFilter_mac_meOg_U3->din1(inQ_V_fu_312_p1);
    matchFilter_mac_meOg_U3->din2(grp_fu_632_p2);
    matchFilter_mac_meOg_U3->ce(ap_var_for_const18);
    matchFilter_mac_meOg_U3->dout(grp_fu_632_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_1_fu_254_p2);
    sensitive << ( a_reg_193 );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state10);
    sensitive << ( out_V_data_V_1_ack_in );
    sensitive << ( out_V_last_V_1_ack_in );

    SC_METHOD(thread_ap_block_state6_io);
    sensitive << ( out_V_data_V_1_ack_in );
    sensitive << ( exitcond_i_fu_272_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_b_fu_278_p2);
    sensitive << ( b_i_reg_229 );

    SC_METHOD(thread_buffIn_data_V_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_8_fu_260_p1 );
    sensitive << ( tmp_7_fu_266_p1 );
    sensitive << ( tmp_2_i_fu_284_p1 );

    SC_METHOD(thread_buffIn_data_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_block_state6_io );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buffIn_data_V_d0);
    sensitive << ( tmp_data_V_reg_641 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( buffIn_data_V_load_reg_670 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buffIn_data_V_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buffIn_last_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_8_fu_260_p1 );
    sensitive << ( tmp_7_fu_266_p1 );

    SC_METHOD(thread_buffIn_last_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buffIn_last_V_d0);
    sensitive << ( tmp_last_V_reg_646 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( buffIn_last_V_load_reg_675 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_buffIn_last_V_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_exitcond_i_fu_272_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_block_state6_io );
    sensitive << ( b_i_reg_229 );

    SC_METHOD(thread_grp_fu_623_p0);
    sensitive << ( tmp_fu_577_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_623_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( p_Val2_1_reg_217 );

    SC_METHOD(thread_grp_fu_632_p0);
    sensitive << ( tmp_fu_577_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_632_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( p_Val2_3_reg_205 );

    SC_METHOD(thread_inI_V_fu_302_p4);
    sensitive << ( buffIn_data_V_q0 );

    SC_METHOD(thread_inQ_V_fu_312_p1);
    sensitive << ( buffIn_data_V_q0 );

    SC_METHOD(thread_in_V_data_V_0_ack_in);
    sensitive << ( in_V_data_V_0_state );

    SC_METHOD(thread_in_V_data_V_0_ack_out);
    sensitive << ( in_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_in_V_data_V_0_data_out);
    sensitive << ( in_V_data_V_0_payload_A );
    sensitive << ( in_V_data_V_0_payload_B );
    sensitive << ( in_V_data_V_0_sel );

    SC_METHOD(thread_in_V_data_V_0_load_A);
    sensitive << ( in_V_data_V_0_sel_wr );
    sensitive << ( in_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_V_data_V_0_load_B);
    sensitive << ( in_V_data_V_0_sel_wr );
    sensitive << ( in_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_in_V_data_V_0_sel);
    sensitive << ( in_V_data_V_0_sel_rd );

    SC_METHOD(thread_in_V_data_V_0_state_cmp_full);
    sensitive << ( in_V_data_V_0_state );

    SC_METHOD(thread_in_V_data_V_0_vld_in);
    sensitive << ( in_r_TVALID );

    SC_METHOD(thread_in_V_data_V_0_vld_out);
    sensitive << ( in_V_data_V_0_state );

    SC_METHOD(thread_in_V_last_V_0_ack_in);
    sensitive << ( in_V_last_V_0_state );

    SC_METHOD(thread_in_V_last_V_0_ack_out);
    sensitive << ( in_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_in_V_last_V_0_data_out);
    sensitive << ( in_V_last_V_0_payload_A );
    sensitive << ( in_V_last_V_0_payload_B );
    sensitive << ( in_V_last_V_0_sel );

    SC_METHOD(thread_in_V_last_V_0_load_A);
    sensitive << ( in_V_last_V_0_sel_wr );
    sensitive << ( in_V_last_V_0_state_cmp_full );

    SC_METHOD(thread_in_V_last_V_0_load_B);
    sensitive << ( in_V_last_V_0_sel_wr );
    sensitive << ( in_V_last_V_0_state_cmp_full );

    SC_METHOD(thread_in_V_last_V_0_sel);
    sensitive << ( in_V_last_V_0_sel_rd );

    SC_METHOD(thread_in_V_last_V_0_state_cmp_full);
    sensitive << ( in_V_last_V_0_state );

    SC_METHOD(thread_in_V_last_V_0_vld_in);
    sensitive << ( in_r_TVALID );

    SC_METHOD(thread_in_V_last_V_0_vld_out);
    sensitive << ( in_V_last_V_0_state );

    SC_METHOD(thread_in_r_TDATA_blk_n);
    sensitive << ( in_V_data_V_0_state );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_in_r_TREADY);
    sensitive << ( in_V_last_V_0_state );

    SC_METHOD(thread_out_V_data_V_1_ack_in);
    sensitive << ( out_V_data_V_1_state );

    SC_METHOD(thread_out_V_data_V_1_ack_out);
    sensitive << ( out_r_TREADY );

    SC_METHOD(thread_out_V_data_V_1_data_out);
    sensitive << ( out_V_data_V_1_payload_A );
    sensitive << ( out_V_data_V_1_payload_B );
    sensitive << ( out_V_data_V_1_sel );

    SC_METHOD(thread_out_V_data_V_1_load_A);
    sensitive << ( out_V_data_V_1_sel_wr );
    sensitive << ( out_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_out_V_data_V_1_load_B);
    sensitive << ( out_V_data_V_1_sel_wr );
    sensitive << ( out_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_out_V_data_V_1_sel);
    sensitive << ( out_V_data_V_1_sel_rd );

    SC_METHOD(thread_out_V_data_V_1_state_cmp_full);
    sensitive << ( out_V_data_V_1_state );

    SC_METHOD(thread_out_V_data_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_i_fu_272_p2 );
    sensitive << ( ap_block_state6_io );

    SC_METHOD(thread_out_V_data_V_1_vld_out);
    sensitive << ( out_V_data_V_1_state );

    SC_METHOD(thread_out_V_last_V_1_ack_in);
    sensitive << ( out_V_last_V_1_state );

    SC_METHOD(thread_out_V_last_V_1_ack_out);
    sensitive << ( out_r_TREADY );

    SC_METHOD(thread_out_V_last_V_1_data_out);
    sensitive << ( out_V_last_V_1_payload_A );
    sensitive << ( out_V_last_V_1_payload_B );
    sensitive << ( out_V_last_V_1_sel );

    SC_METHOD(thread_out_V_last_V_1_load_A);
    sensitive << ( out_V_last_V_1_sel_wr );
    sensitive << ( out_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_out_V_last_V_1_load_B);
    sensitive << ( out_V_last_V_1_sel_wr );
    sensitive << ( out_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_out_V_last_V_1_sel);
    sensitive << ( out_V_last_V_1_sel_rd );

    SC_METHOD(thread_out_V_last_V_1_state_cmp_full);
    sensitive << ( out_V_last_V_1_state );

    SC_METHOD(thread_out_V_last_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_i_fu_272_p2 );
    sensitive << ( ap_block_state6_io );

    SC_METHOD(thread_out_V_last_V_1_vld_out);
    sensitive << ( out_V_last_V_1_state );

    SC_METHOD(thread_out_r_TDATA);
    sensitive << ( out_V_data_V_1_data_out );

    SC_METHOD(thread_out_r_TDATA_blk_n);
    sensitive << ( out_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_i_fu_272_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_r_TLAST);
    sensitive << ( out_V_last_V_1_data_out );

    SC_METHOD(thread_out_r_TVALID);
    sensitive << ( out_V_last_V_1_state );

    SC_METHOD(thread_p_Result_s_fu_293_p3);
    sensitive << ( p_Val2_3_reg_205 );
    sensitive << ( p_Val2_1_reg_217 );

    SC_METHOD(thread_tmp_2_i_fu_284_p1);
    sensitive << ( b_i_reg_229 );

    SC_METHOD(thread_tmp_4_fu_289_p1);
    sensitive << ( b_i_reg_229 );

    SC_METHOD(thread_tmp_7_fu_266_p1);
    sensitive << ( a_reg_193 );

    SC_METHOD(thread_tmp_8_fu_260_p1);
    sensitive << ( a_1_fu_254_p2 );

    SC_METHOD(thread_tmp_fu_577_p1);
    sensitive << ( merge_i_fu_316_p130 );

    SC_METHOD(thread_tmp_s_fu_248_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( a_reg_193 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( in_V_data_V_0_vld_out );
    sensitive << ( out_V_data_V_1_ack_in );
    sensitive << ( out_V_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_i_fu_272_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_248_p2 );
    sensitive << ( ap_block_state6_io );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const18);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const5);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const8);

    SC_THREAD(thread_ap_var_for_const9);

    SC_THREAD(thread_ap_var_for_const10);

    SC_THREAD(thread_ap_var_for_const11);

    SC_THREAD(thread_ap_var_for_const12);

    SC_THREAD(thread_ap_var_for_const13);

    SC_THREAD(thread_ap_var_for_const14);

    SC_THREAD(thread_ap_var_for_const15);

    SC_THREAD(thread_ap_var_for_const16);

    SC_THREAD(thread_ap_var_for_const17);

    in_V_data_V_0_sel_rd = SC_LOGIC_0;
    in_V_data_V_0_sel_wr = SC_LOGIC_0;
    in_V_data_V_0_state = "00";
    in_V_last_V_0_sel_rd = SC_LOGIC_0;
    in_V_last_V_0_sel_wr = SC_LOGIC_0;
    in_V_last_V_0_state = "00";
    out_V_data_V_1_sel_rd = SC_LOGIC_0;
    out_V_data_V_1_sel_wr = SC_LOGIC_0;
    out_V_data_V_1_state = "00";
    out_V_last_V_1_sel_rd = SC_LOGIC_0;
    out_V_last_V_1_sel_wr = SC_LOGIC_0;
    out_V_last_V_1_state = "00";
    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matchFilter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, in_r_TDATA, "(port)in_r_TDATA");
    sc_trace(mVcdFile, in_r_TVALID, "(port)in_r_TVALID");
    sc_trace(mVcdFile, in_r_TREADY, "(port)in_r_TREADY");
    sc_trace(mVcdFile, in_r_TLAST, "(port)in_r_TLAST");
    sc_trace(mVcdFile, out_r_TDATA, "(port)out_r_TDATA");
    sc_trace(mVcdFile, out_r_TVALID, "(port)out_r_TVALID");
    sc_trace(mVcdFile, out_r_TREADY, "(port)out_r_TREADY");
    sc_trace(mVcdFile, out_r_TLAST, "(port)out_r_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, in_V_data_V_0_data_out, "in_V_data_V_0_data_out");
    sc_trace(mVcdFile, in_V_data_V_0_vld_in, "in_V_data_V_0_vld_in");
    sc_trace(mVcdFile, in_V_data_V_0_vld_out, "in_V_data_V_0_vld_out");
    sc_trace(mVcdFile, in_V_data_V_0_ack_in, "in_V_data_V_0_ack_in");
    sc_trace(mVcdFile, in_V_data_V_0_ack_out, "in_V_data_V_0_ack_out");
    sc_trace(mVcdFile, in_V_data_V_0_payload_A, "in_V_data_V_0_payload_A");
    sc_trace(mVcdFile, in_V_data_V_0_payload_B, "in_V_data_V_0_payload_B");
    sc_trace(mVcdFile, in_V_data_V_0_sel_rd, "in_V_data_V_0_sel_rd");
    sc_trace(mVcdFile, in_V_data_V_0_sel_wr, "in_V_data_V_0_sel_wr");
    sc_trace(mVcdFile, in_V_data_V_0_sel, "in_V_data_V_0_sel");
    sc_trace(mVcdFile, in_V_data_V_0_load_A, "in_V_data_V_0_load_A");
    sc_trace(mVcdFile, in_V_data_V_0_load_B, "in_V_data_V_0_load_B");
    sc_trace(mVcdFile, in_V_data_V_0_state, "in_V_data_V_0_state");
    sc_trace(mVcdFile, in_V_data_V_0_state_cmp_full, "in_V_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, in_V_last_V_0_data_out, "in_V_last_V_0_data_out");
    sc_trace(mVcdFile, in_V_last_V_0_vld_in, "in_V_last_V_0_vld_in");
    sc_trace(mVcdFile, in_V_last_V_0_vld_out, "in_V_last_V_0_vld_out");
    sc_trace(mVcdFile, in_V_last_V_0_ack_in, "in_V_last_V_0_ack_in");
    sc_trace(mVcdFile, in_V_last_V_0_ack_out, "in_V_last_V_0_ack_out");
    sc_trace(mVcdFile, in_V_last_V_0_payload_A, "in_V_last_V_0_payload_A");
    sc_trace(mVcdFile, in_V_last_V_0_payload_B, "in_V_last_V_0_payload_B");
    sc_trace(mVcdFile, in_V_last_V_0_sel_rd, "in_V_last_V_0_sel_rd");
    sc_trace(mVcdFile, in_V_last_V_0_sel_wr, "in_V_last_V_0_sel_wr");
    sc_trace(mVcdFile, in_V_last_V_0_sel, "in_V_last_V_0_sel");
    sc_trace(mVcdFile, in_V_last_V_0_load_A, "in_V_last_V_0_load_A");
    sc_trace(mVcdFile, in_V_last_V_0_load_B, "in_V_last_V_0_load_B");
    sc_trace(mVcdFile, in_V_last_V_0_state, "in_V_last_V_0_state");
    sc_trace(mVcdFile, in_V_last_V_0_state_cmp_full, "in_V_last_V_0_state_cmp_full");
    sc_trace(mVcdFile, out_V_data_V_1_data_out, "out_V_data_V_1_data_out");
    sc_trace(mVcdFile, out_V_data_V_1_vld_in, "out_V_data_V_1_vld_in");
    sc_trace(mVcdFile, out_V_data_V_1_vld_out, "out_V_data_V_1_vld_out");
    sc_trace(mVcdFile, out_V_data_V_1_ack_in, "out_V_data_V_1_ack_in");
    sc_trace(mVcdFile, out_V_data_V_1_ack_out, "out_V_data_V_1_ack_out");
    sc_trace(mVcdFile, out_V_data_V_1_payload_A, "out_V_data_V_1_payload_A");
    sc_trace(mVcdFile, out_V_data_V_1_payload_B, "out_V_data_V_1_payload_B");
    sc_trace(mVcdFile, out_V_data_V_1_sel_rd, "out_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, out_V_data_V_1_sel_wr, "out_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, out_V_data_V_1_sel, "out_V_data_V_1_sel");
    sc_trace(mVcdFile, out_V_data_V_1_load_A, "out_V_data_V_1_load_A");
    sc_trace(mVcdFile, out_V_data_V_1_load_B, "out_V_data_V_1_load_B");
    sc_trace(mVcdFile, out_V_data_V_1_state, "out_V_data_V_1_state");
    sc_trace(mVcdFile, out_V_data_V_1_state_cmp_full, "out_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, out_V_last_V_1_data_out, "out_V_last_V_1_data_out");
    sc_trace(mVcdFile, out_V_last_V_1_vld_in, "out_V_last_V_1_vld_in");
    sc_trace(mVcdFile, out_V_last_V_1_vld_out, "out_V_last_V_1_vld_out");
    sc_trace(mVcdFile, out_V_last_V_1_ack_in, "out_V_last_V_1_ack_in");
    sc_trace(mVcdFile, out_V_last_V_1_ack_out, "out_V_last_V_1_ack_out");
    sc_trace(mVcdFile, out_V_last_V_1_payload_A, "out_V_last_V_1_payload_A");
    sc_trace(mVcdFile, out_V_last_V_1_payload_B, "out_V_last_V_1_payload_B");
    sc_trace(mVcdFile, out_V_last_V_1_sel_rd, "out_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, out_V_last_V_1_sel_wr, "out_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, out_V_last_V_1_sel, "out_V_last_V_1_sel");
    sc_trace(mVcdFile, out_V_last_V_1_load_A, "out_V_last_V_1_load_A");
    sc_trace(mVcdFile, out_V_last_V_1_load_B, "out_V_last_V_1_load_B");
    sc_trace(mVcdFile, out_V_last_V_1_state, "out_V_last_V_1_state");
    sc_trace(mVcdFile, out_V_last_V_1_state_cmp_full, "out_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, in_r_TDATA_blk_n, "in_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, out_r_TDATA_blk_n, "out_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, exitcond_i_fu_272_p2, "exitcond_i_fu_272_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_data_V_reg_641, "tmp_data_V_reg_641");
    sc_trace(mVcdFile, tmp_last_V_reg_646, "tmp_last_V_reg_646");
    sc_trace(mVcdFile, a_1_fu_254_p2, "a_1_fu_254_p2");
    sc_trace(mVcdFile, a_1_reg_655, "a_1_reg_655");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_s_fu_248_p2, "tmp_s_fu_248_p2");
    sc_trace(mVcdFile, buffIn_data_V_q0, "buffIn_data_V_q0");
    sc_trace(mVcdFile, buffIn_data_V_load_reg_670, "buffIn_data_V_load_reg_670");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, buffIn_last_V_q0, "buffIn_last_V_q0");
    sc_trace(mVcdFile, buffIn_last_V_load_reg_675, "buffIn_last_V_load_reg_675");
    sc_trace(mVcdFile, b_fu_278_p2, "b_fu_278_p2");
    sc_trace(mVcdFile, b_reg_683, "b_reg_683");
    sc_trace(mVcdFile, ap_block_state6_io, "ap_block_state6_io");
    sc_trace(mVcdFile, tmp_4_fu_289_p1, "tmp_4_fu_289_p1");
    sc_trace(mVcdFile, tmp_4_reg_693, "tmp_4_reg_693");
    sc_trace(mVcdFile, p_Result_s_fu_293_p3, "p_Result_s_fu_293_p3");
    sc_trace(mVcdFile, tmp_fu_577_p1, "tmp_fu_577_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, buffIn_data_V_address0, "buffIn_data_V_address0");
    sc_trace(mVcdFile, buffIn_data_V_ce0, "buffIn_data_V_ce0");
    sc_trace(mVcdFile, buffIn_data_V_we0, "buffIn_data_V_we0");
    sc_trace(mVcdFile, buffIn_data_V_d0, "buffIn_data_V_d0");
    sc_trace(mVcdFile, buffIn_last_V_address0, "buffIn_last_V_address0");
    sc_trace(mVcdFile, buffIn_last_V_ce0, "buffIn_last_V_ce0");
    sc_trace(mVcdFile, buffIn_last_V_we0, "buffIn_last_V_we0");
    sc_trace(mVcdFile, buffIn_last_V_d0, "buffIn_last_V_d0");
    sc_trace(mVcdFile, a_reg_193, "a_reg_193");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, p_Val2_3_reg_205, "p_Val2_3_reg_205");
    sc_trace(mVcdFile, p_Val2_1_reg_217, "p_Val2_1_reg_217");
    sc_trace(mVcdFile, b_i_reg_229, "b_i_reg_229");
    sc_trace(mVcdFile, tmp_8_fu_260_p1, "tmp_8_fu_260_p1");
    sc_trace(mVcdFile, tmp_7_fu_266_p1, "tmp_7_fu_266_p1");
    sc_trace(mVcdFile, tmp_2_i_fu_284_p1, "tmp_2_i_fu_284_p1");
    sc_trace(mVcdFile, ap_block_state10, "ap_block_state10");
    sc_trace(mVcdFile, merge_i_fu_316_p130, "merge_i_fu_316_p130");
    sc_trace(mVcdFile, inI_V_fu_302_p4, "inI_V_fu_302_p4");
    sc_trace(mVcdFile, inQ_V_fu_312_p1, "inQ_V_fu_312_p1");
    sc_trace(mVcdFile, grp_fu_623_p3, "grp_fu_623_p3");
    sc_trace(mVcdFile, grp_fu_632_p3, "grp_fu_632_p3");
    sc_trace(mVcdFile, grp_fu_623_p0, "grp_fu_623_p0");
    sc_trace(mVcdFile, grp_fu_623_p2, "grp_fu_623_p2");
    sc_trace(mVcdFile, grp_fu_632_p0, "grp_fu_632_p0");
    sc_trace(mVcdFile, grp_fu_632_p2, "grp_fu_632_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matchFilter.hdltvin.dat");
    mHdltvoutHandle.open("matchFilter.hdltvout.dat");
}

matchFilter::~matchFilter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete buffIn_data_V_U;
    delete buffIn_last_V_U;
    delete matchFilter_mux_1dEe_U1;
    delete matchFilter_mac_meOg_U2;
    delete matchFilter_mac_meOg_U3;
}

void matchFilter::thread_ap_var_for_const18() {
    ap_var_for_const18 = ap_const_logic_1;
}

void matchFilter::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv16_0;
}

void matchFilter::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv16_FFFF;
}

void matchFilter::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv16_FFFE;
}

void matchFilter::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv16_FFFD;
}

void matchFilter::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv16_FFFC;
}

void matchFilter::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv16_1;
}

void matchFilter::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_lv16_4;
}

void matchFilter::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv16_7;
}

void matchFilter::thread_ap_var_for_const8() {
    ap_var_for_const8 = ap_const_lv16_A;
}

void matchFilter::thread_ap_var_for_const9() {
    ap_var_for_const9 = ap_const_lv16_D;
}

void matchFilter::thread_ap_var_for_const10() {
    ap_var_for_const10 = ap_const_lv16_10;
}

void matchFilter::thread_ap_var_for_const11() {
    ap_var_for_const11 = ap_const_lv16_14;
}

void matchFilter::thread_ap_var_for_const12() {
    ap_var_for_const12 = ap_const_lv16_17;
}

void matchFilter::thread_ap_var_for_const13() {
    ap_var_for_const13 = ap_const_lv16_1A;
}

void matchFilter::thread_ap_var_for_const14() {
    ap_var_for_const14 = ap_const_lv16_1C;
}

void matchFilter::thread_ap_var_for_const15() {
    ap_var_for_const15 = ap_const_lv16_1E;
}

void matchFilter::thread_ap_var_for_const16() {
    ap_var_for_const16 = ap_const_lv16_1F;
}

void matchFilter::thread_ap_var_for_const17() {
    ap_var_for_const17 = ap_const_lv16_20;
}

void matchFilter::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_reg_193 = a_1_reg_655.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(in_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
        a_reg_193 = ap_const_lv7_7F;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        b_i_reg_229 = b_reg_683.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        b_i_reg_229 = ap_const_lv8_0;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_V_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_vld_out.read()))) {
            in_V_data_V_0_sel_rd =  (sc_logic) (~in_V_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_V_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_ack_in.read()))) {
            in_V_data_V_0_sel_wr =  (sc_logic) (~in_V_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_V_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_2)))) {
            in_V_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_1)))) {
            in_V_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(in_V_data_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_ack_out.read()))))) {
            in_V_data_V_0_state = ap_const_lv2_3;
        } else {
            in_V_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_V_last_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_vld_out.read()))) {
            in_V_last_V_0_sel_rd =  (sc_logic) (~in_V_last_V_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_V_last_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_ack_in.read()))) {
            in_V_last_V_0_sel_wr =  (sc_logic) (~in_V_last_V_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        in_V_last_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, in_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, in_V_last_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, in_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, in_V_last_V_0_state.read())))) {
            in_V_last_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, in_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, in_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, in_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_V_last_V_0_state.read())))) {
            in_V_last_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, in_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, in_V_last_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, in_V_last_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_last_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, in_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_ack_out.read()))))) {
            in_V_last_V_0_state = ap_const_lv2_3;
        } else {
            in_V_last_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_out.read()))) {
            out_V_data_V_1_sel_rd =  (sc_logic) (~out_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_in.read()))) {
            out_V_data_V_1_sel_wr =  (sc_logic) (~out_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_V_data_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_V_data_V_1_state.read())))) {
            out_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_V_data_V_1_state.read())))) {
            out_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_V_data_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_V_data_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()))))) {
            out_V_data_V_1_state = ap_const_lv2_3;
        } else {
            out_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_vld_out.read()))) {
            out_V_last_V_1_sel_rd =  (sc_logic) (~out_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_ack_in.read()))) {
            out_V_last_V_1_sel_wr =  (sc_logic) (~out_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        out_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_V_last_V_1_state.read())))) {
            out_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_V_1_state.read())))) {
            out_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_ack_out.read()))))) {
            out_V_last_V_1_state = ap_const_lv2_3;
        } else {
            out_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_Val2_1_reg_217 = grp_fu_623_p3.read().range(20, 5);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        p_Val2_1_reg_217 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_Val2_3_reg_205 = grp_fu_632_p3.read().range(20, 5);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        p_Val2_3_reg_205 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_248_p2.read()))) {
        a_1_reg_655 = a_1_fu_254_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0))) {
        b_reg_683 = b_fu_278_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffIn_data_V_load_reg_670 = buffIn_data_V_q0.read();
        buffIn_last_V_load_reg_675 = buffIn_last_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_load_A.read())) {
        in_V_data_V_0_payload_A = in_r_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_load_B.read())) {
        in_V_data_V_0_payload_B = in_r_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_load_A.read())) {
        in_V_last_V_0_payload_A = in_r_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_load_B.read())) {
        in_V_last_V_0_payload_B = in_r_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_load_A.read())) {
        out_V_data_V_1_payload_A = p_Result_s_fu_293_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_load_B.read())) {
        out_V_data_V_1_payload_B = p_Result_s_fu_293_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_load_A.read())) {
        out_V_last_V_1_payload_A = tmp_last_V_reg_646.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_load_B.read())) {
        out_V_last_V_1_payload_B = tmp_last_V_reg_646.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_272_p2.read()))) {
        tmp_4_reg_693 = tmp_4_fu_289_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(in_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
        tmp_data_V_reg_641 = in_V_data_V_0_data_out.read();
        tmp_last_V_reg_646 = in_V_last_V_0_data_out.read();
    }
}

void matchFilter::thread_a_1_fu_254_p2() {
    a_1_fu_254_p2 = (!a_reg_193.read().is_01() || !ap_const_lv7_7F.is_01())? sc_lv<7>(): (sc_biguint<7>(a_reg_193.read()) + sc_bigint<7>(ap_const_lv7_7F));
}

void matchFilter::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void matchFilter::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matchFilter::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matchFilter::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matchFilter::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matchFilter::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void matchFilter::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void matchFilter::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void matchFilter::thread_ap_block_state10() {
    ap_block_state10 = (esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_ack_in.read()));
}

void matchFilter::thread_ap_block_state6_io() {
    ap_block_state6_io = (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_272_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_in.read()));
}

void matchFilter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void matchFilter::thread_b_fu_278_p2() {
    b_fu_278_p2 = (!b_i_reg_229.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(b_i_reg_229.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void matchFilter::thread_buffIn_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buffIn_data_V_address0 =  (sc_lv<7>) (tmp_2_i_fu_284_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buffIn_data_V_address0 =  (sc_lv<7>) (tmp_7_fu_266_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        buffIn_data_V_address0 =  (sc_lv<7>) (ap_const_lv64_0);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_248_p2.read()))) {
        buffIn_data_V_address0 =  (sc_lv<7>) (tmp_8_fu_260_p1.read());
    } else {
        buffIn_data_V_address0 = "XXXXXXX";
    }
}

void matchFilter::thread_buffIn_data_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_248_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read())))) {
        buffIn_data_V_ce0 = ap_const_logic_1;
    } else {
        buffIn_data_V_ce0 = ap_const_logic_0;
    }
}

void matchFilter::thread_buffIn_data_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buffIn_data_V_d0 = buffIn_data_V_load_reg_670.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        buffIn_data_V_d0 = tmp_data_V_reg_641.read();
    } else {
        buffIn_data_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void matchFilter::thread_buffIn_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read())))) {
        buffIn_data_V_we0 = ap_const_logic_1;
    } else {
        buffIn_data_V_we0 = ap_const_logic_0;
    }
}

void matchFilter::thread_buffIn_last_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buffIn_last_V_address0 =  (sc_lv<7>) (tmp_7_fu_266_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        buffIn_last_V_address0 =  (sc_lv<7>) (ap_const_lv64_0);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_248_p2.read()))) {
        buffIn_last_V_address0 =  (sc_lv<7>) (tmp_8_fu_260_p1.read());
    } else {
        buffIn_last_V_address0 = "XXXXXXX";
    }
}

void matchFilter::thread_buffIn_last_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_248_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read())))) {
        buffIn_last_V_ce0 = ap_const_logic_1;
    } else {
        buffIn_last_V_ce0 = ap_const_logic_0;
    }
}

void matchFilter::thread_buffIn_last_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buffIn_last_V_d0 = buffIn_last_V_load_reg_675.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
        buffIn_last_V_d0 = tmp_last_V_reg_646.read();
    } else {
        buffIn_last_V_d0 =  (sc_lv<1>) ("X");
    }
}

void matchFilter::thread_buffIn_last_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read())))) {
        buffIn_last_V_we0 = ap_const_logic_1;
    } else {
        buffIn_last_V_we0 = ap_const_logic_0;
    }
}

void matchFilter::thread_exitcond_i_fu_272_p2() {
    exitcond_i_fu_272_p2 = (!b_i_reg_229.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(b_i_reg_229.read() == ap_const_lv8_80);
}

void matchFilter::thread_grp_fu_623_p0() {
    grp_fu_623_p0 =  (sc_lv<16>) (tmp_fu_577_p1.read());
}

void matchFilter::thread_grp_fu_623_p2() {
    grp_fu_623_p2 = esl_concat<16,5>(p_Val2_1_reg_217.read(), ap_const_lv5_0);
}

void matchFilter::thread_grp_fu_632_p0() {
    grp_fu_632_p0 =  (sc_lv<16>) (tmp_fu_577_p1.read());
}

void matchFilter::thread_grp_fu_632_p2() {
    grp_fu_632_p2 = esl_concat<16,5>(p_Val2_3_reg_205.read(), ap_const_lv5_0);
}

void matchFilter::thread_inI_V_fu_302_p4() {
    inI_V_fu_302_p4 = buffIn_data_V_q0.read().range(31, 16);
}

void matchFilter::thread_inQ_V_fu_312_p1() {
    inQ_V_fu_312_p1 = buffIn_data_V_q0.read().range(16-1, 0);
}

void matchFilter::thread_in_V_data_V_0_ack_in() {
    in_V_data_V_0_ack_in = in_V_data_V_0_state.read()[1];
}

void matchFilter::thread_in_V_data_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(in_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
        in_V_data_V_0_ack_out = ap_const_logic_1;
    } else {
        in_V_data_V_0_ack_out = ap_const_logic_0;
    }
}

void matchFilter::thread_in_V_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_V_data_V_0_sel.read())) {
        in_V_data_V_0_data_out = in_V_data_V_0_payload_B.read();
    } else {
        in_V_data_V_0_data_out = in_V_data_V_0_payload_A.read();
    }
}

void matchFilter::thread_in_V_data_V_0_load_A() {
    in_V_data_V_0_load_A = (in_V_data_V_0_state_cmp_full.read() & ~in_V_data_V_0_sel_wr.read());
}

void matchFilter::thread_in_V_data_V_0_load_B() {
    in_V_data_V_0_load_B = (in_V_data_V_0_sel_wr.read() & in_V_data_V_0_state_cmp_full.read());
}

void matchFilter::thread_in_V_data_V_0_sel() {
    in_V_data_V_0_sel = in_V_data_V_0_sel_rd.read();
}

void matchFilter::thread_in_V_data_V_0_state_cmp_full() {
    in_V_data_V_0_state_cmp_full =  (sc_logic) ((!in_V_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(in_V_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void matchFilter::thread_in_V_data_V_0_vld_in() {
    in_V_data_V_0_vld_in = in_r_TVALID.read();
}

void matchFilter::thread_in_V_data_V_0_vld_out() {
    in_V_data_V_0_vld_out = in_V_data_V_0_state.read()[0];
}

void matchFilter::thread_in_V_last_V_0_ack_in() {
    in_V_last_V_0_ack_in = in_V_last_V_0_state.read()[1];
}

void matchFilter::thread_in_V_last_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(in_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
        in_V_last_V_0_ack_out = ap_const_logic_1;
    } else {
        in_V_last_V_0_ack_out = ap_const_logic_0;
    }
}

void matchFilter::thread_in_V_last_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, in_V_last_V_0_sel.read())) {
        in_V_last_V_0_data_out = in_V_last_V_0_payload_B.read();
    } else {
        in_V_last_V_0_data_out = in_V_last_V_0_payload_A.read();
    }
}

void matchFilter::thread_in_V_last_V_0_load_A() {
    in_V_last_V_0_load_A = (in_V_last_V_0_state_cmp_full.read() & ~in_V_last_V_0_sel_wr.read());
}

void matchFilter::thread_in_V_last_V_0_load_B() {
    in_V_last_V_0_load_B = (in_V_last_V_0_sel_wr.read() & in_V_last_V_0_state_cmp_full.read());
}

void matchFilter::thread_in_V_last_V_0_sel() {
    in_V_last_V_0_sel = in_V_last_V_0_sel_rd.read();
}

void matchFilter::thread_in_V_last_V_0_state_cmp_full() {
    in_V_last_V_0_state_cmp_full =  (sc_logic) ((!in_V_last_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(in_V_last_V_0_state.read() != ap_const_lv2_1))[0];
}

void matchFilter::thread_in_V_last_V_0_vld_in() {
    in_V_last_V_0_vld_in = in_r_TVALID.read();
}

void matchFilter::thread_in_V_last_V_0_vld_out() {
    in_V_last_V_0_vld_out = in_V_last_V_0_state.read()[0];
}

void matchFilter::thread_in_r_TDATA_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        in_r_TDATA_blk_n = in_V_data_V_0_state.read()[0];
    } else {
        in_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void matchFilter::thread_in_r_TREADY() {
    in_r_TREADY = in_V_last_V_0_state.read()[1];
}

void matchFilter::thread_out_V_data_V_1_ack_in() {
    out_V_data_V_1_ack_in = out_V_data_V_1_state.read()[1];
}

void matchFilter::thread_out_V_data_V_1_ack_out() {
    out_V_data_V_1_ack_out = out_r_TREADY.read();
}

void matchFilter::thread_out_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_sel.read())) {
        out_V_data_V_1_data_out = out_V_data_V_1_payload_B.read();
    } else {
        out_V_data_V_1_data_out = out_V_data_V_1_payload_A.read();
    }
}

void matchFilter::thread_out_V_data_V_1_load_A() {
    out_V_data_V_1_load_A = (out_V_data_V_1_state_cmp_full.read() & ~out_V_data_V_1_sel_wr.read());
}

void matchFilter::thread_out_V_data_V_1_load_B() {
    out_V_data_V_1_load_B = (out_V_data_V_1_sel_wr.read() & out_V_data_V_1_state_cmp_full.read());
}

void matchFilter::thread_out_V_data_V_1_sel() {
    out_V_data_V_1_sel = out_V_data_V_1_sel_rd.read();
}

void matchFilter::thread_out_V_data_V_1_state_cmp_full() {
    out_V_data_V_1_state_cmp_full =  (sc_logic) ((!out_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void matchFilter::thread_out_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_272_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0))) {
        out_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        out_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void matchFilter::thread_out_V_data_V_1_vld_out() {
    out_V_data_V_1_vld_out = out_V_data_V_1_state.read()[0];
}

void matchFilter::thread_out_V_last_V_1_ack_in() {
    out_V_last_V_1_ack_in = out_V_last_V_1_state.read()[1];
}

void matchFilter::thread_out_V_last_V_1_ack_out() {
    out_V_last_V_1_ack_out = out_r_TREADY.read();
}

void matchFilter::thread_out_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_V_1_sel.read())) {
        out_V_last_V_1_data_out = out_V_last_V_1_payload_B.read();
    } else {
        out_V_last_V_1_data_out = out_V_last_V_1_payload_A.read();
    }
}

void matchFilter::thread_out_V_last_V_1_load_A() {
    out_V_last_V_1_load_A = (out_V_last_V_1_state_cmp_full.read() & ~out_V_last_V_1_sel_wr.read());
}

void matchFilter::thread_out_V_last_V_1_load_B() {
    out_V_last_V_1_load_B = (out_V_last_V_1_sel_wr.read() & out_V_last_V_1_state_cmp_full.read());
}

void matchFilter::thread_out_V_last_V_1_sel() {
    out_V_last_V_1_sel = out_V_last_V_1_sel_rd.read();
}

void matchFilter::thread_out_V_last_V_1_state_cmp_full() {
    out_V_last_V_1_state_cmp_full =  (sc_logic) ((!out_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void matchFilter::thread_out_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_272_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0))) {
        out_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        out_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void matchFilter::thread_out_V_last_V_1_vld_out() {
    out_V_last_V_1_vld_out = out_V_last_V_1_state.read()[0];
}

void matchFilter::thread_out_r_TDATA() {
    out_r_TDATA = out_V_data_V_1_data_out.read();
}

void matchFilter::thread_out_r_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_272_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_r_TDATA_blk_n = out_V_data_V_1_state.read()[1];
    } else {
        out_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void matchFilter::thread_out_r_TLAST() {
    out_r_TLAST = out_V_last_V_1_data_out.read();
}

void matchFilter::thread_out_r_TVALID() {
    out_r_TVALID = out_V_last_V_1_state.read()[0];
}

void matchFilter::thread_p_Result_s_fu_293_p3() {
    p_Result_s_fu_293_p3 = esl_concat<16,16>(p_Val2_1_reg_217.read(), p_Val2_3_reg_205.read());
}

void matchFilter::thread_tmp_2_i_fu_284_p1() {
    tmp_2_i_fu_284_p1 = esl_zext<64,8>(b_i_reg_229.read());
}

void matchFilter::thread_tmp_4_fu_289_p1() {
    tmp_4_fu_289_p1 = b_i_reg_229.read().range(7-1, 0);
}

void matchFilter::thread_tmp_7_fu_266_p1() {
    tmp_7_fu_266_p1 = esl_zext<64,7>(a_reg_193.read());
}

void matchFilter::thread_tmp_8_fu_260_p1() {
    tmp_8_fu_260_p1 = esl_zext<64,7>(a_1_fu_254_p2.read());
}

void matchFilter::thread_tmp_fu_577_p1() {
    tmp_fu_577_p1 = esl_sext<21,16>(merge_i_fu_316_p130.read());
}

void matchFilter::thread_tmp_s_fu_248_p2() {
    tmp_s_fu_248_p2 = (!a_reg_193.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(a_reg_193.read() == ap_const_lv7_0);
}

void matchFilter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(in_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_248_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_272_p2.read()) && esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_block_state6_io.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_272_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_V_1_ack_in.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<10>) ("XXXXXXXXXX");
            break;
    }
}

void matchFilter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TDATA\" :  \"" << in_r_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TVALID\" :  \"" << in_r_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"in_r_TREADY\" :  \"" << in_r_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TLAST\" :  \"" << in_r_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TDATA\" :  \"" << out_r_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TVALID\" :  \"" << out_r_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_r_TREADY\" :  \"" << out_r_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TLAST\" :  \"" << out_r_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

