// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "correlator.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic correlator::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic correlator::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> correlator::ap_ST_fsm_pp0_stage0 = "1";
const bool correlator::ap_const_boolean_1 = true;
const sc_lv<1> correlator::ap_const_lv1_0 = "0";
const sc_lv<1> correlator::ap_const_lv1_1 = "1";
const sc_lv<2> correlator::ap_const_lv2_0 = "00";
const sc_lv<2> correlator::ap_const_lv2_2 = "10";
const sc_lv<2> correlator::ap_const_lv2_3 = "11";
const sc_lv<2> correlator::ap_const_lv2_1 = "1";
const sc_lv<16> correlator::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> correlator::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool correlator::ap_const_boolean_0 = false;
const sc_lv<4> correlator::ap_const_lv4_0 = "0000";
const sc_lv<5> correlator::ap_const_lv5_0 = "00000";
const sc_lv<32> correlator::ap_const_lv32_1 = "1";

correlator::correlator(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( i_data_TVALID );
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_predicate_op12_read_state1 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( i_data_TVALID );
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_predicate_op12_read_state1 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( i_data_TVALID );
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_predicate_op12_read_state1 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( i_data_TVALID );
    sensitive << ( ap_predicate_op12_read_state1 );

    SC_METHOD(thread_ap_block_state2_io);
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( ap_predicate_op351_write_state2 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( ap_predicate_op375_write_state3 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_predicate_op12_read_state1);
    sensitive << ( currentState );
    sensitive << ( tmp_nbreadreq_fu_424_p4 );

    SC_METHOD(thread_ap_predicate_op351_write_state2);
    sensitive << ( currentState_load_reg_2124 );
    sensitive << ( tmp_reg_2128 );
    sensitive << ( phaseClass_V_read_reg_2116 );

    SC_METHOD(thread_ap_predicate_op375_write_state3);
    sensitive << ( ap_reg_pp0_iter1_currentState_load_reg_2124 );
    sensitive << ( ap_reg_pp0_iter1_tmp_reg_2128 );
    sensitive << ( ap_reg_pp0_iter1_phaseClass_V_read_reg_2116 );

    SC_METHOD(thread_ap_reset_idle_pp0);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_currentState_load_load_fu_458_p1);
    sensitive << ( currentState );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_i_data_TDATA_blk_n);
    sensitive << ( i_data_TVALID );
    sensitive << ( currentState );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_nbreadreq_fu_424_p4 );

    SC_METHOD(thread_i_data_TREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_predicate_op12_read_state1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_loc_V_fu_2081_p2);
    sensitive << ( tmp7_fu_2035_p2 );
    sensitive << ( tmp10_cast_fu_2077_p1 );

    SC_METHOD(thread_o_data_TDATA);
    sensitive << ( o_data_V_data_V_1_data_out );

    SC_METHOD(thread_o_data_TDATA_blk_n);
    sensitive << ( o_data_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( currentState_load_reg_2124 );
    sensitive << ( tmp_reg_2128 );
    sensitive << ( phaseClass_V_read_reg_2116 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_currentState_load_reg_2124 );
    sensitive << ( ap_reg_pp0_iter1_tmp_reg_2128 );
    sensitive << ( ap_reg_pp0_iter1_phaseClass_V_read_reg_2116 );

    SC_METHOD(thread_o_data_TLAST);
    sensitive << ( o_data_V_last_V_1_data_out );

    SC_METHOD(thread_o_data_TVALID);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_o_data_V_data_V_1_ack_in);
    sensitive << ( o_data_V_data_V_1_state );

    SC_METHOD(thread_o_data_V_data_V_1_ack_out);
    sensitive << ( o_data_TREADY );

    SC_METHOD(thread_o_data_V_data_V_1_data_out);
    sensitive << ( o_data_V_data_V_1_payload_A );
    sensitive << ( o_data_V_data_V_1_payload_B );
    sensitive << ( o_data_V_data_V_1_sel );

    SC_METHOD(thread_o_data_V_data_V_1_load_A);
    sensitive << ( o_data_V_data_V_1_sel_wr );
    sensitive << ( o_data_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_o_data_V_data_V_1_load_B);
    sensitive << ( o_data_V_data_V_1_sel_wr );
    sensitive << ( o_data_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_o_data_V_data_V_1_sel);
    sensitive << ( o_data_V_data_V_1_sel_rd );

    SC_METHOD(thread_o_data_V_data_V_1_state_cmp_full);
    sensitive << ( o_data_V_data_V_1_state );

    SC_METHOD(thread_o_data_V_data_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op351_write_state2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_o_data_V_data_V_1_vld_out);
    sensitive << ( o_data_V_data_V_1_state );

    SC_METHOD(thread_o_data_V_last_V_1_ack_in);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_o_data_V_last_V_1_ack_out);
    sensitive << ( o_data_TREADY );

    SC_METHOD(thread_o_data_V_last_V_1_data_out);
    sensitive << ( o_data_V_last_V_1_payload_A );
    sensitive << ( o_data_V_last_V_1_payload_B );
    sensitive << ( o_data_V_last_V_1_sel );

    SC_METHOD(thread_o_data_V_last_V_1_load_A);
    sensitive << ( o_data_V_last_V_1_sel_wr );
    sensitive << ( o_data_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_o_data_V_last_V_1_load_B);
    sensitive << ( o_data_V_last_V_1_sel_wr );
    sensitive << ( o_data_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_o_data_V_last_V_1_sel);
    sensitive << ( o_data_V_last_V_1_sel_rd );

    SC_METHOD(thread_o_data_V_last_V_1_state_cmp_full);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_o_data_V_last_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op351_write_state2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_o_data_V_last_V_1_vld_out);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_start_V_read_read_fu_418_p2);
    sensitive << ( start_V );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp10_cast_fu_2077_p1);
    sensitive << ( tmp4_fu_2071_p2 );

    SC_METHOD(thread_tmp11_cast_fu_2047_p1);
    sensitive << ( tmp1_fu_2041_p2 );

    SC_METHOD(thread_tmp12_cast_fu_2067_p1);
    sensitive << ( tmp3_fu_2061_p2 );

    SC_METHOD(thread_tmp13_cast_fu_2057_p1);
    sensitive << ( tmp2_fu_2051_p2 );

    SC_METHOD(thread_tmp1_fu_2041_p2);
    sensitive << ( tmp_2_cast_fu_1862_p1 );
    sensitive << ( tmp_71_7_cast_fu_1898_p1 );

    SC_METHOD(thread_tmp2_fu_2051_p2);
    sensitive << ( tmp_71_4_cast_fu_2015_p1 );
    sensitive << ( tmp_71_2_cast_fu_1874_p1 );

    SC_METHOD(thread_tmp3_fu_2061_p2);
    sensitive << ( tmp_71_5_cast_fu_1886_p1 );
    sensitive << ( tmp13_cast_fu_2057_p1 );

    SC_METHOD(thread_tmp4_fu_2071_p2);
    sensitive << ( tmp11_cast_fu_2047_p1 );
    sensitive << ( tmp12_cast_fu_2067_p1 );

    SC_METHOD(thread_tmp7_fu_2035_p2);
    sensitive << ( tmp8_fu_2019_p2 );
    sensitive << ( tmp9_cast_fu_2031_p1 );

    SC_METHOD(thread_tmp8_fu_2019_p2);
    sensitive << ( corHelperI_V );
    sensitive << ( tmp_71_1_cast_fu_1972_p1 );

    SC_METHOD(thread_tmp9_cast_fu_2031_p1);
    sensitive << ( tmp9_fu_2025_p2 );

    SC_METHOD(thread_tmp9_fu_2025_p2);
    sensitive << ( tmp_71_cast_fu_1950_p1 );
    sensitive << ( tmp_71_3_cast_fu_1994_p1 );

    SC_METHOD(thread_tmp_1_fu_470_p1);
    sensitive << ( i_data_TDATA );

    SC_METHOD(thread_tmp_2_cast_fu_1862_p1);
    sensitive << ( tmp_2_fu_1854_p3 );

    SC_METHOD(thread_tmp_2_fu_1854_p3);
    sensitive << ( phaseClass0_V_14 );

    SC_METHOD(thread_tmp_71_1_cast_fu_1972_p1);
    sensitive << ( tmp_71_1_fu_1964_p3 );

    SC_METHOD(thread_tmp_71_1_fu_1964_p3);
    sensitive << ( phaseClass0_V_1 );

    SC_METHOD(thread_tmp_71_2_cast_fu_1874_p1);
    sensitive << ( tmp_71_2_fu_1866_p3 );

    SC_METHOD(thread_tmp_71_2_fu_1866_p3);
    sensitive << ( phaseClass0_V_12 );

    SC_METHOD(thread_tmp_71_3_cast_fu_1994_p1);
    sensitive << ( tmp_71_3_fu_1986_p3 );

    SC_METHOD(thread_tmp_71_3_fu_1986_p3);
    sensitive << ( phaseClass0_V_0 );

    SC_METHOD(thread_tmp_71_4_cast_fu_2015_p1);
    sensitive << ( tmp_71_4_fu_2008_p3 );

    SC_METHOD(thread_tmp_71_4_fu_2008_p3);
    sensitive << ( tmp_1_reg_2137 );

    SC_METHOD(thread_tmp_71_5_cast_fu_1886_p1);
    sensitive << ( tmp_71_5_fu_1878_p3 );

    SC_METHOD(thread_tmp_71_5_fu_1878_p3);
    sensitive << ( phaseClass0_V_9 );

    SC_METHOD(thread_tmp_71_7_cast_fu_1898_p1);
    sensitive << ( tmp_71_7_fu_1890_p3 );

    SC_METHOD(thread_tmp_71_7_fu_1890_p3);
    sensitive << ( phaseClass0_V_7 );

    SC_METHOD(thread_tmp_71_cast_fu_1950_p1);
    sensitive << ( tmp_71_s_fu_1942_p3 );

    SC_METHOD(thread_tmp_71_s_fu_1942_p3);
    sensitive << ( phaseClass0_V_2 );

    SC_METHOD(thread_tmp_nbreadreq_fu_424_p4);
    sensitive << ( i_data_TVALID );

    SC_METHOD(thread_tmp_s_fu_2104_p2);
    sensitive << ( loadCount_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    o_data_V_data_V_1_sel_rd = SC_LOGIC_0;
    o_data_V_data_V_1_sel_wr = SC_LOGIC_0;
    o_data_V_data_V_1_state = "00";
    o_data_V_last_V_1_sel_rd = SC_LOGIC_0;
    o_data_V_last_V_1_sel_wr = SC_LOGIC_0;
    o_data_V_last_V_1_state = "00";
    currentState = "0";
    phaseClass0_V_14 = "0000000000000000";
    phaseClass0_V_13 = "0000000000000000";
    phaseClass0_V_12 = "0000000000000000";
    phaseClass0_V_11 = "0000000000000000";
    phaseClass0_V_10 = "0000000000000000";
    phaseClass0_V_9 = "0000000000000000";
    phaseClass0_V_8 = "0000000000000000";
    phaseClass0_V_7 = "0000000000000000";
    phaseClass0_V_6 = "0000000000000000";
    phaseClass0_V_5 = "0000000000000000";
    phaseClass0_V_4 = "0000000000000000";
    phaseClass0_V_3 = "0000000000000000";
    phaseClass0_V_2 = "0000000000000000";
    phaseClass0_V_1 = "0000000000000000";
    phaseClass0_V_0 = "0000000000000000";
    corHelperI_V = "00000000000000000000000000000000";
    loadCount_V = "00000000000000000000000000000000";
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "correlator_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, i_data_TDATA, "(port)i_data_TDATA");
    sc_trace(mVcdFile, i_data_TVALID, "(port)i_data_TVALID");
    sc_trace(mVcdFile, i_data_TREADY, "(port)i_data_TREADY");
    sc_trace(mVcdFile, i_data_TLAST, "(port)i_data_TLAST");
    sc_trace(mVcdFile, o_data_TDATA, "(port)o_data_TDATA");
    sc_trace(mVcdFile, o_data_TVALID, "(port)o_data_TVALID");
    sc_trace(mVcdFile, o_data_TREADY, "(port)o_data_TREADY");
    sc_trace(mVcdFile, o_data_TLAST, "(port)o_data_TLAST");
    sc_trace(mVcdFile, start_V, "(port)start_V");
    sc_trace(mVcdFile, phaseClass_V, "(port)phaseClass_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, o_data_V_data_V_1_data_out, "o_data_V_data_V_1_data_out");
    sc_trace(mVcdFile, o_data_V_data_V_1_vld_in, "o_data_V_data_V_1_vld_in");
    sc_trace(mVcdFile, o_data_V_data_V_1_vld_out, "o_data_V_data_V_1_vld_out");
    sc_trace(mVcdFile, o_data_V_data_V_1_ack_in, "o_data_V_data_V_1_ack_in");
    sc_trace(mVcdFile, o_data_V_data_V_1_ack_out, "o_data_V_data_V_1_ack_out");
    sc_trace(mVcdFile, o_data_V_data_V_1_payload_A, "o_data_V_data_V_1_payload_A");
    sc_trace(mVcdFile, o_data_V_data_V_1_payload_B, "o_data_V_data_V_1_payload_B");
    sc_trace(mVcdFile, o_data_V_data_V_1_sel_rd, "o_data_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, o_data_V_data_V_1_sel_wr, "o_data_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, o_data_V_data_V_1_sel, "o_data_V_data_V_1_sel");
    sc_trace(mVcdFile, o_data_V_data_V_1_load_A, "o_data_V_data_V_1_load_A");
    sc_trace(mVcdFile, o_data_V_data_V_1_load_B, "o_data_V_data_V_1_load_B");
    sc_trace(mVcdFile, o_data_V_data_V_1_state, "o_data_V_data_V_1_state");
    sc_trace(mVcdFile, o_data_V_data_V_1_state_cmp_full, "o_data_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, o_data_V_last_V_1_data_out, "o_data_V_last_V_1_data_out");
    sc_trace(mVcdFile, o_data_V_last_V_1_vld_in, "o_data_V_last_V_1_vld_in");
    sc_trace(mVcdFile, o_data_V_last_V_1_vld_out, "o_data_V_last_V_1_vld_out");
    sc_trace(mVcdFile, o_data_V_last_V_1_ack_in, "o_data_V_last_V_1_ack_in");
    sc_trace(mVcdFile, o_data_V_last_V_1_ack_out, "o_data_V_last_V_1_ack_out");
    sc_trace(mVcdFile, o_data_V_last_V_1_payload_A, "o_data_V_last_V_1_payload_A");
    sc_trace(mVcdFile, o_data_V_last_V_1_payload_B, "o_data_V_last_V_1_payload_B");
    sc_trace(mVcdFile, o_data_V_last_V_1_sel_rd, "o_data_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, o_data_V_last_V_1_sel_wr, "o_data_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, o_data_V_last_V_1_sel, "o_data_V_last_V_1_sel");
    sc_trace(mVcdFile, o_data_V_last_V_1_load_A, "o_data_V_last_V_1_load_A");
    sc_trace(mVcdFile, o_data_V_last_V_1_load_B, "o_data_V_last_V_1_load_B");
    sc_trace(mVcdFile, o_data_V_last_V_1_state, "o_data_V_last_V_1_state");
    sc_trace(mVcdFile, o_data_V_last_V_1_state_cmp_full, "o_data_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, currentState, "currentState");
    sc_trace(mVcdFile, phaseClass0_V_14, "phaseClass0_V_14");
    sc_trace(mVcdFile, phaseClass0_V_13, "phaseClass0_V_13");
    sc_trace(mVcdFile, phaseClass0_V_12, "phaseClass0_V_12");
    sc_trace(mVcdFile, phaseClass0_V_11, "phaseClass0_V_11");
    sc_trace(mVcdFile, phaseClass0_V_10, "phaseClass0_V_10");
    sc_trace(mVcdFile, phaseClass0_V_9, "phaseClass0_V_9");
    sc_trace(mVcdFile, phaseClass0_V_8, "phaseClass0_V_8");
    sc_trace(mVcdFile, phaseClass0_V_7, "phaseClass0_V_7");
    sc_trace(mVcdFile, phaseClass0_V_6, "phaseClass0_V_6");
    sc_trace(mVcdFile, phaseClass0_V_5, "phaseClass0_V_5");
    sc_trace(mVcdFile, phaseClass0_V_4, "phaseClass0_V_4");
    sc_trace(mVcdFile, phaseClass0_V_3, "phaseClass0_V_3");
    sc_trace(mVcdFile, phaseClass0_V_2, "phaseClass0_V_2");
    sc_trace(mVcdFile, phaseClass0_V_1, "phaseClass0_V_1");
    sc_trace(mVcdFile, phaseClass0_V_0, "phaseClass0_V_0");
    sc_trace(mVcdFile, corHelperI_V, "corHelperI_V");
    sc_trace(mVcdFile, loadCount_V, "loadCount_V");
    sc_trace(mVcdFile, i_data_TDATA_blk_n, "i_data_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, currentState_load_load_fu_458_p1, "currentState_load_load_fu_458_p1");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_424_p4, "tmp_nbreadreq_fu_424_p4");
    sc_trace(mVcdFile, o_data_TDATA_blk_n, "o_data_TDATA_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, currentState_load_reg_2124, "currentState_load_reg_2124");
    sc_trace(mVcdFile, tmp_reg_2128, "tmp_reg_2128");
    sc_trace(mVcdFile, phaseClass_V_read_reg_2116, "phaseClass_V_read_reg_2116");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_currentState_load_reg_2124, "ap_reg_pp0_iter1_currentState_load_reg_2124");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_reg_2128, "ap_reg_pp0_iter1_tmp_reg_2128");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_phaseClass_V_read_reg_2116, "ap_reg_pp0_iter1_phaseClass_V_read_reg_2116");
    sc_trace(mVcdFile, ap_predicate_op12_read_state1, "ap_predicate_op12_read_state1");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_predicate_op351_write_state2, "ap_predicate_op351_write_state2");
    sc_trace(mVcdFile, ap_block_state2_io, "ap_block_state2_io");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_predicate_op375_write_state3, "ap_predicate_op375_write_state3");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, start_V_read_read_fu_418_p2, "start_V_read_read_fu_418_p2");
    sc_trace(mVcdFile, tmp_last_V_reg_2132, "tmp_last_V_reg_2132");
    sc_trace(mVcdFile, tmp_1_fu_470_p1, "tmp_1_fu_470_p1");
    sc_trace(mVcdFile, tmp_1_reg_2137, "tmp_1_reg_2137");
    sc_trace(mVcdFile, loc_V_fu_2081_p2, "loc_V_fu_2081_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, tmp_s_fu_2104_p2, "tmp_s_fu_2104_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_2_fu_1854_p3, "tmp_2_fu_1854_p3");
    sc_trace(mVcdFile, tmp_71_2_fu_1866_p3, "tmp_71_2_fu_1866_p3");
    sc_trace(mVcdFile, tmp_71_5_fu_1878_p3, "tmp_71_5_fu_1878_p3");
    sc_trace(mVcdFile, tmp_71_7_fu_1890_p3, "tmp_71_7_fu_1890_p3");
    sc_trace(mVcdFile, tmp_71_s_fu_1942_p3, "tmp_71_s_fu_1942_p3");
    sc_trace(mVcdFile, tmp_71_1_fu_1964_p3, "tmp_71_1_fu_1964_p3");
    sc_trace(mVcdFile, tmp_71_3_fu_1986_p3, "tmp_71_3_fu_1986_p3");
    sc_trace(mVcdFile, tmp_71_4_fu_2008_p3, "tmp_71_4_fu_2008_p3");
    sc_trace(mVcdFile, tmp_71_1_cast_fu_1972_p1, "tmp_71_1_cast_fu_1972_p1");
    sc_trace(mVcdFile, tmp_71_cast_fu_1950_p1, "tmp_71_cast_fu_1950_p1");
    sc_trace(mVcdFile, tmp_71_3_cast_fu_1994_p1, "tmp_71_3_cast_fu_1994_p1");
    sc_trace(mVcdFile, tmp9_fu_2025_p2, "tmp9_fu_2025_p2");
    sc_trace(mVcdFile, tmp8_fu_2019_p2, "tmp8_fu_2019_p2");
    sc_trace(mVcdFile, tmp9_cast_fu_2031_p1, "tmp9_cast_fu_2031_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_1862_p1, "tmp_2_cast_fu_1862_p1");
    sc_trace(mVcdFile, tmp_71_7_cast_fu_1898_p1, "tmp_71_7_cast_fu_1898_p1");
    sc_trace(mVcdFile, tmp1_fu_2041_p2, "tmp1_fu_2041_p2");
    sc_trace(mVcdFile, tmp_71_4_cast_fu_2015_p1, "tmp_71_4_cast_fu_2015_p1");
    sc_trace(mVcdFile, tmp_71_2_cast_fu_1874_p1, "tmp_71_2_cast_fu_1874_p1");
    sc_trace(mVcdFile, tmp2_fu_2051_p2, "tmp2_fu_2051_p2");
    sc_trace(mVcdFile, tmp_71_5_cast_fu_1886_p1, "tmp_71_5_cast_fu_1886_p1");
    sc_trace(mVcdFile, tmp13_cast_fu_2057_p1, "tmp13_cast_fu_2057_p1");
    sc_trace(mVcdFile, tmp3_fu_2061_p2, "tmp3_fu_2061_p2");
    sc_trace(mVcdFile, tmp11_cast_fu_2047_p1, "tmp11_cast_fu_2047_p1");
    sc_trace(mVcdFile, tmp12_cast_fu_2067_p1, "tmp12_cast_fu_2067_p1");
    sc_trace(mVcdFile, tmp4_fu_2071_p2, "tmp4_fu_2071_p2");
    sc_trace(mVcdFile, tmp7_fu_2035_p2, "tmp7_fu_2035_p2");
    sc_trace(mVcdFile, tmp10_cast_fu_2077_p1, "tmp10_cast_fu_2077_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("correlator.hdltvin.dat");
    mHdltvoutHandle.open("correlator.hdltvout.dat");
}

correlator::~correlator() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void correlator::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        corHelperI_V = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            corHelperI_V = loc_V_fu_2081_p2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        currentState = ap_const_lv1_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, currentState_load_load_fu_458_p1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, start_V_read_read_fu_418_p2.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
            currentState = ap_const_lv1_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        loadCount_V = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_currentState_load_reg_2124.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_tmp_reg_2128.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            loadCount_V = tmp_s_fu_2104_p2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_out.read()))) {
            o_data_V_data_V_1_sel_rd =  (sc_logic) (~o_data_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_in.read()))) {
            o_data_V_data_V_1_sel_wr =  (sc_logic) (~o_data_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            o_data_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            o_data_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()))))) {
            o_data_V_data_V_1_state = ap_const_lv2_3;
        } else {
            o_data_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_out.read()))) {
            o_data_V_last_V_1_sel_rd =  (sc_logic) (~o_data_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_in.read()))) {
            o_data_V_last_V_1_sel_wr =  (sc_logic) (~o_data_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, o_data_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, o_data_V_last_V_1_state.read())))) {
            o_data_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, o_data_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, o_data_V_last_V_1_state.read())))) {
            o_data_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, o_data_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, o_data_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, o_data_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()))))) {
            o_data_V_last_V_1_state = ap_const_lv2_3;
        } else {
            o_data_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_0 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_0 = tmp_1_reg_2137.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_1 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_1 = phaseClass0_V_0.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_10 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_10 = phaseClass0_V_9.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_11 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_11 = phaseClass0_V_10.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_12 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_12 = phaseClass0_V_11.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_13 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_13 = phaseClass0_V_12.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_14 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_14 = phaseClass0_V_13.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_2 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_2 = phaseClass0_V_1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_3 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_3 = phaseClass0_V_2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_4 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_4 = phaseClass0_V_3.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_5 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_5 = phaseClass0_V_4.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_6 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_6 = phaseClass0_V_5.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_7 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_7 = phaseClass0_V_6.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_8 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_8 = phaseClass0_V_7.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_9 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            phaseClass0_V_9 = phaseClass0_V_8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_currentState_load_reg_2124 = currentState_load_reg_2124.read();
        ap_reg_pp0_iter1_phaseClass_V_read_reg_2116 = phaseClass_V_read_reg_2116.read();
        ap_reg_pp0_iter1_tmp_reg_2128 = tmp_reg_2128.read();
        currentState_load_reg_2124 = currentState.read();
        phaseClass_V_read_reg_2116 = phaseClass_V.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_load_A.read())) {
        o_data_V_data_V_1_payload_A = loc_V_fu_2081_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_load_B.read())) {
        o_data_V_data_V_1_payload_B = loc_V_fu_2081_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_load_A.read())) {
        o_data_V_last_V_1_payload_A = tmp_last_V_reg_2132.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_load_B.read())) {
        o_data_V_last_V_1_payload_B = tmp_last_V_reg_2132.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op12_read_state1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_1_reg_2137 = tmp_1_fu_470_p1.read();
        tmp_last_V_reg_2132 = i_data_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_reg_2128 = tmp_nbreadreq_fu_424_p4.read();
    }
}

void correlator::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void correlator::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void correlator::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op12_read_state1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()))));
}

void correlator::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op12_read_state1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))));
}

void correlator::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op12_read_state1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))));
}

void correlator::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op12_read_state1.read()));
}

void correlator::thread_ap_block_state2_io() {
    ap_block_state2_io = (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()));
}

void correlator::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void correlator::thread_ap_block_state3_io() {
    ap_block_state3_io = (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op375_write_state3.read()));
}

void correlator::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()));
}

void correlator::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void correlator::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void correlator::thread_ap_predicate_op12_read_state1() {
    ap_predicate_op12_read_state1 = (esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_424_p4.read()));
}

void correlator::thread_ap_predicate_op351_write_state2() {
    ap_predicate_op351_write_state2 = (esl_seteq<1,1,1>(ap_const_lv1_1, currentState_load_reg_2124.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_2128.read()) && esl_seteq<1,4,4>(phaseClass_V_read_reg_2116.read(), ap_const_lv4_0));
}

void correlator::thread_ap_predicate_op375_write_state3() {
    ap_predicate_op375_write_state3 = (esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_currentState_load_reg_2124.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_tmp_reg_2128.read()) && esl_seteq<1,4,4>(ap_const_lv4_0, ap_reg_pp0_iter1_phaseClass_V_read_reg_2116.read()));
}

void correlator::thread_ap_reset_idle_pp0() {
    if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void correlator::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void correlator::thread_currentState_load_load_fu_458_p1() {
    currentState_load_load_fu_458_p1 = currentState.read();
}

void correlator::thread_i_data_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_424_p4.read()))) {
        i_data_TDATA_blk_n = i_data_TVALID.read();
    } else {
        i_data_TDATA_blk_n = ap_const_logic_1;
    }
}

void correlator::thread_i_data_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op12_read_state1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_data_TREADY = ap_const_logic_1;
    } else {
        i_data_TREADY = ap_const_logic_0;
    }
}

void correlator::thread_loc_V_fu_2081_p2() {
    loc_V_fu_2081_p2 = (!tmp7_fu_2035_p2.read().is_01() || !tmp10_cast_fu_2077_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp7_fu_2035_p2.read()) + sc_bigint<32>(tmp10_cast_fu_2077_p1.read()));
}

void correlator::thread_o_data_TDATA() {
    o_data_TDATA = o_data_V_data_V_1_data_out.read();
}

void correlator::thread_o_data_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, currentState_load_reg_2124.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_2128.read()) && 
          esl_seteq<1,4,4>(phaseClass_V_read_reg_2116.read(), ap_const_lv4_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_currentState_load_reg_2124.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_tmp_reg_2128.read()) && 
          esl_seteq<1,4,4>(ap_const_lv4_0, ap_reg_pp0_iter1_phaseClass_V_read_reg_2116.read())))) {
        o_data_TDATA_blk_n = o_data_V_data_V_1_state.read()[1];
    } else {
        o_data_TDATA_blk_n = ap_const_logic_1;
    }
}

void correlator::thread_o_data_TLAST() {
    o_data_TLAST = o_data_V_last_V_1_data_out.read();
}

void correlator::thread_o_data_TVALID() {
    o_data_TVALID = o_data_V_last_V_1_state.read()[0];
}

void correlator::thread_o_data_V_data_V_1_ack_in() {
    o_data_V_data_V_1_ack_in = o_data_V_data_V_1_state.read()[1];
}

void correlator::thread_o_data_V_data_V_1_ack_out() {
    o_data_V_data_V_1_ack_out = o_data_TREADY.read();
}

void correlator::thread_o_data_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_sel.read())) {
        o_data_V_data_V_1_data_out = o_data_V_data_V_1_payload_B.read();
    } else {
        o_data_V_data_V_1_data_out = o_data_V_data_V_1_payload_A.read();
    }
}

void correlator::thread_o_data_V_data_V_1_load_A() {
    o_data_V_data_V_1_load_A = (o_data_V_data_V_1_state_cmp_full.read() & ~o_data_V_data_V_1_sel_wr.read());
}

void correlator::thread_o_data_V_data_V_1_load_B() {
    o_data_V_data_V_1_load_B = (o_data_V_data_V_1_sel_wr.read() & o_data_V_data_V_1_state_cmp_full.read());
}

void correlator::thread_o_data_V_data_V_1_sel() {
    o_data_V_data_V_1_sel = o_data_V_data_V_1_sel_rd.read();
}

void correlator::thread_o_data_V_data_V_1_state_cmp_full() {
    o_data_V_data_V_1_state_cmp_full =  (sc_logic) ((!o_data_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(o_data_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void correlator::thread_o_data_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        o_data_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        o_data_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void correlator::thread_o_data_V_data_V_1_vld_out() {
    o_data_V_data_V_1_vld_out = o_data_V_data_V_1_state.read()[0];
}

void correlator::thread_o_data_V_last_V_1_ack_in() {
    o_data_V_last_V_1_ack_in = o_data_V_last_V_1_state.read()[1];
}

void correlator::thread_o_data_V_last_V_1_ack_out() {
    o_data_V_last_V_1_ack_out = o_data_TREADY.read();
}

void correlator::thread_o_data_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_sel.read())) {
        o_data_V_last_V_1_data_out = o_data_V_last_V_1_payload_B.read();
    } else {
        o_data_V_last_V_1_data_out = o_data_V_last_V_1_payload_A.read();
    }
}

void correlator::thread_o_data_V_last_V_1_load_A() {
    o_data_V_last_V_1_load_A = (o_data_V_last_V_1_state_cmp_full.read() & ~o_data_V_last_V_1_sel_wr.read());
}

void correlator::thread_o_data_V_last_V_1_load_B() {
    o_data_V_last_V_1_load_B = (o_data_V_last_V_1_sel_wr.read() & o_data_V_last_V_1_state_cmp_full.read());
}

void correlator::thread_o_data_V_last_V_1_sel() {
    o_data_V_last_V_1_sel = o_data_V_last_V_1_sel_rd.read();
}

void correlator::thread_o_data_V_last_V_1_state_cmp_full() {
    o_data_V_last_V_1_state_cmp_full =  (sc_logic) ((!o_data_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(o_data_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void correlator::thread_o_data_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op351_write_state2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        o_data_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        o_data_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void correlator::thread_o_data_V_last_V_1_vld_out() {
    o_data_V_last_V_1_vld_out = o_data_V_last_V_1_state.read()[0];
}

void correlator::thread_start_V_read_read_fu_418_p2() {
    start_V_read_read_fu_418_p2 = start_V.read();
}

void correlator::thread_tmp10_cast_fu_2077_p1() {
    tmp10_cast_fu_2077_p1 = esl_sext<32,24>(tmp4_fu_2071_p2.read());
}

void correlator::thread_tmp11_cast_fu_2047_p1() {
    tmp11_cast_fu_2047_p1 = esl_sext<24,22>(tmp1_fu_2041_p2.read());
}

void correlator::thread_tmp12_cast_fu_2067_p1() {
    tmp12_cast_fu_2067_p1 = esl_sext<24,23>(tmp3_fu_2061_p2.read());
}

void correlator::thread_tmp13_cast_fu_2057_p1() {
    tmp13_cast_fu_2057_p1 = esl_sext<23,22>(tmp2_fu_2051_p2.read());
}

void correlator::thread_tmp1_fu_2041_p2() {
    tmp1_fu_2041_p2 = (!tmp_2_cast_fu_1862_p1.read().is_01() || !tmp_71_7_cast_fu_1898_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(tmp_2_cast_fu_1862_p1.read()) + sc_bigint<22>(tmp_71_7_cast_fu_1898_p1.read()));
}

void correlator::thread_tmp2_fu_2051_p2() {
    tmp2_fu_2051_p2 = (!tmp_71_4_cast_fu_2015_p1.read().is_01() || !tmp_71_2_cast_fu_1874_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(tmp_71_4_cast_fu_2015_p1.read()) + sc_bigint<22>(tmp_71_2_cast_fu_1874_p1.read()));
}

void correlator::thread_tmp3_fu_2061_p2() {
    tmp3_fu_2061_p2 = (!tmp_71_5_cast_fu_1886_p1.read().is_01() || !tmp13_cast_fu_2057_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(tmp_71_5_cast_fu_1886_p1.read()) + sc_bigint<23>(tmp13_cast_fu_2057_p1.read()));
}

void correlator::thread_tmp4_fu_2071_p2() {
    tmp4_fu_2071_p2 = (!tmp11_cast_fu_2047_p1.read().is_01() || !tmp12_cast_fu_2067_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(tmp11_cast_fu_2047_p1.read()) + sc_bigint<24>(tmp12_cast_fu_2067_p1.read()));
}

void correlator::thread_tmp7_fu_2035_p2() {
    tmp7_fu_2035_p2 = (!tmp8_fu_2019_p2.read().is_01() || !tmp9_cast_fu_2031_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp8_fu_2019_p2.read()) + sc_bigint<32>(tmp9_cast_fu_2031_p1.read()));
}

void correlator::thread_tmp8_fu_2019_p2() {
    tmp8_fu_2019_p2 = (!tmp_71_1_cast_fu_1972_p1.read().is_01() || !corHelperI_V.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_71_1_cast_fu_1972_p1.read()) + sc_biguint<32>(corHelperI_V.read()));
}

void correlator::thread_tmp9_cast_fu_2031_p1() {
    tmp9_cast_fu_2031_p1 = esl_sext<32,22>(tmp9_fu_2025_p2.read());
}

void correlator::thread_tmp9_fu_2025_p2() {
    tmp9_fu_2025_p2 = (!tmp_71_cast_fu_1950_p1.read().is_01() || !tmp_71_3_cast_fu_1994_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(tmp_71_cast_fu_1950_p1.read()) + sc_bigint<22>(tmp_71_3_cast_fu_1994_p1.read()));
}

void correlator::thread_tmp_1_fu_470_p1() {
    tmp_1_fu_470_p1 = i_data_TDATA.read().range(16-1, 0);
}

void correlator::thread_tmp_2_cast_fu_1862_p1() {
    tmp_2_cast_fu_1862_p1 = esl_sext<22,21>(tmp_2_fu_1854_p3.read());
}

void correlator::thread_tmp_2_fu_1854_p3() {
    tmp_2_fu_1854_p3 = esl_concat<16,5>(phaseClass0_V_14.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_1_cast_fu_1972_p1() {
    tmp_71_1_cast_fu_1972_p1 = esl_sext<32,21>(tmp_71_1_fu_1964_p3.read());
}

void correlator::thread_tmp_71_1_fu_1964_p3() {
    tmp_71_1_fu_1964_p3 = esl_concat<16,5>(phaseClass0_V_1.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_2_cast_fu_1874_p1() {
    tmp_71_2_cast_fu_1874_p1 = esl_sext<22,21>(tmp_71_2_fu_1866_p3.read());
}

void correlator::thread_tmp_71_2_fu_1866_p3() {
    tmp_71_2_fu_1866_p3 = esl_concat<16,5>(phaseClass0_V_12.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_3_cast_fu_1994_p1() {
    tmp_71_3_cast_fu_1994_p1 = esl_sext<22,21>(tmp_71_3_fu_1986_p3.read());
}

void correlator::thread_tmp_71_3_fu_1986_p3() {
    tmp_71_3_fu_1986_p3 = esl_concat<16,5>(phaseClass0_V_0.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_4_cast_fu_2015_p1() {
    tmp_71_4_cast_fu_2015_p1 = esl_sext<22,21>(tmp_71_4_fu_2008_p3.read());
}

void correlator::thread_tmp_71_4_fu_2008_p3() {
    tmp_71_4_fu_2008_p3 = esl_concat<16,5>(tmp_1_reg_2137.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_5_cast_fu_1886_p1() {
    tmp_71_5_cast_fu_1886_p1 = esl_sext<23,21>(tmp_71_5_fu_1878_p3.read());
}

void correlator::thread_tmp_71_5_fu_1878_p3() {
    tmp_71_5_fu_1878_p3 = esl_concat<16,5>(phaseClass0_V_9.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_7_cast_fu_1898_p1() {
    tmp_71_7_cast_fu_1898_p1 = esl_sext<22,21>(tmp_71_7_fu_1890_p3.read());
}

void correlator::thread_tmp_71_7_fu_1890_p3() {
    tmp_71_7_fu_1890_p3 = esl_concat<16,5>(phaseClass0_V_7.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_71_cast_fu_1950_p1() {
    tmp_71_cast_fu_1950_p1 = esl_sext<22,21>(tmp_71_s_fu_1942_p3.read());
}

void correlator::thread_tmp_71_s_fu_1942_p3() {
    tmp_71_s_fu_1942_p3 = esl_concat<16,5>(phaseClass0_V_2.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_nbreadreq_fu_424_p4() {
    tmp_nbreadreq_fu_424_p4 =  (sc_lv<1>) ((i_data_TVALID.read()));
}

void correlator::thread_tmp_s_fu_2104_p2() {
    tmp_s_fu_2104_p2 = (!loadCount_V.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(loadCount_V.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void correlator::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void correlator::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i_data_TDATA\" :  \"" << i_data_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i_data_TVALID\" :  \"" << i_data_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"i_data_TREADY\" :  \"" << i_data_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i_data_TLAST\" :  \"" << i_data_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"o_data_TDATA\" :  \"" << o_data_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"o_data_TVALID\" :  \"" << o_data_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"o_data_TREADY\" :  \"" << o_data_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"o_data_TLAST\" :  \"" << o_data_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"start_V\" :  \"" << start_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"phaseClass_V\" :  \"" << phaseClass_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

