// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "correlator.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic correlator::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic correlator::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> correlator::ap_ST_fsm_pp0_stage0 = "1";
const bool correlator::ap_const_boolean_1 = true;
const sc_lv<1> correlator::ap_const_lv1_0 = "0";
const sc_lv<1> correlator::ap_const_lv1_1 = "1";
const sc_lv<2> correlator::ap_const_lv2_0 = "00";
const sc_lv<2> correlator::ap_const_lv2_2 = "10";
const sc_lv<2> correlator::ap_const_lv2_3 = "11";
const sc_lv<2> correlator::ap_const_lv2_1 = "1";
const sc_lv<16> correlator::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> correlator::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool correlator::ap_const_boolean_0 = false;
const sc_lv<4> correlator::ap_const_lv4_0 = "0000";
const sc_lv<5> correlator::ap_const_lv5_0 = "00000";
const sc_lv<32> correlator::ap_const_lv32_10 = "10000";
const sc_lv<32> correlator::ap_const_lv32_1A = "11010";
const sc_lv<32> correlator::ap_const_lv32_1000 = "1000000000000";
const sc_lv<32> correlator::ap_const_lv32_1 = "1";

correlator::correlator(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( i_data_TVALID );
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_predicate_op33_read_state1 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( i_data_TVALID );
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_predicate_op33_read_state1 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_block_state4_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( i_data_TVALID );
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_predicate_op33_read_state1 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_block_state4_io );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( i_data_TVALID );
    sensitive << ( ap_predicate_op33_read_state1 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( ap_predicate_op70_write_state3 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_io);
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( ap_predicate_op93_write_state4 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);
    sensitive << ( o_data_V_data_V_1_ack_in );
    sensitive << ( o_data_V_last_V_1_ack_in );

    SC_METHOD(thread_ap_condition_162);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_condition_304);
    sensitive << ( currentState );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_corState_flag_1_phi_fu_173_p4);
    sensitive << ( tmp_nbreadreq_fu_130_p4 );
    sensitive << ( ap_phi_mux_corState_flag_phi_fu_162_p4 );
    sensitive << ( ap_phi_reg_pp0_iter0_corState_flag_1_reg_170 );
    sensitive << ( ap_condition_304 );

    SC_METHOD(thread_ap_phi_mux_corState_flag_2_phi_fu_195_p4);
    sensitive << ( currentState );
    sensitive << ( currentState_load_load_fu_299_p1 );
    sensitive << ( ap_phi_mux_corState_flag_phi_fu_162_p4 );
    sensitive << ( ap_phi_mux_corState_flag_1_phi_fu_173_p4 );
    sensitive << ( ap_phi_reg_pp0_iter0_corState_flag_2_reg_192 );
    sensitive << ( ap_condition_162 );

    SC_METHOD(thread_ap_phi_mux_corState_flag_phi_fu_162_p4);
    sensitive << ( corState_load_load_fu_221_p1 );
    sensitive << ( ap_phi_reg_pp0_iter0_corState_flag_reg_159 );
    sensitive << ( ap_condition_162 );

    SC_METHOD(thread_ap_phi_mux_corState_new_1_phi_fu_184_p4);
    sensitive << ( tmp_nbreadreq_fu_130_p4 );
    sensitive << ( ap_phi_reg_pp0_iter0_corState_new_1_reg_181 );
    sensitive << ( ap_condition_304 );

    SC_METHOD(thread_ap_phi_mux_corState_new_2_phi_fu_207_p4);
    sensitive << ( currentState );
    sensitive << ( currentState_load_load_fu_299_p1 );
    sensitive << ( ap_phi_mux_corState_new_1_phi_fu_184_p4 );
    sensitive << ( ap_phi_reg_pp0_iter0_corState_new_2_reg_204 );
    sensitive << ( ap_condition_162 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_corState_flag_1_reg_170);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_corState_flag_2_reg_192);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_corState_flag_reg_159);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_corState_new_1_reg_181);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_corState_new_2_reg_204);

    SC_METHOD(thread_ap_predicate_op33_read_state1);
    sensitive << ( currentState );
    sensitive << ( tmp_nbreadreq_fu_130_p4 );

    SC_METHOD(thread_ap_predicate_op70_write_state3);
    sensitive << ( ap_reg_pp0_iter1_corState_load_reg_476 );
    sensitive << ( ap_reg_pp0_iter1_cond_reg_485 );
    sensitive << ( tmp_4_reg_502 );

    SC_METHOD(thread_ap_predicate_op93_write_state4);
    sensitive << ( ap_reg_pp0_iter2_corState_load_reg_476 );
    sensitive << ( ap_reg_pp0_iter2_cond_reg_485 );
    sensitive << ( ap_reg_pp0_iter2_tmp_4_reg_502 );

    SC_METHOD(thread_ap_reset_idle_pp0);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_cond_fu_241_p2);
    sensitive << ( phaseClass_V );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( corState_load_load_fu_221_p1 );

    SC_METHOD(thread_corState_load_load_fu_221_p1);
    sensitive << ( corState );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_currentState_load_load_fu_299_p1);
    sensitive << ( currentState );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_i_data_TDATA_blk_n);
    sensitive << ( i_data_TVALID );
    sensitive << ( currentState );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_nbreadreq_fu_130_p4 );

    SC_METHOD(thread_i_data_TREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_predicate_op33_read_state1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_o_data_TDATA);
    sensitive << ( o_data_V_data_V_1_data_out );

    SC_METHOD(thread_o_data_TDATA_blk_n);
    sensitive << ( o_data_V_data_V_1_state );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_corState_load_reg_476 );
    sensitive << ( ap_reg_pp0_iter1_cond_reg_485 );
    sensitive << ( tmp_4_reg_502 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_reg_pp0_iter2_corState_load_reg_476 );
    sensitive << ( ap_reg_pp0_iter2_cond_reg_485 );
    sensitive << ( ap_reg_pp0_iter2_tmp_4_reg_502 );

    SC_METHOD(thread_o_data_TLAST);
    sensitive << ( o_data_V_last_V_1_data_out );

    SC_METHOD(thread_o_data_TVALID);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_o_data_V_data_V_1_ack_in);
    sensitive << ( o_data_V_data_V_1_state );

    SC_METHOD(thread_o_data_V_data_V_1_ack_out);
    sensitive << ( o_data_TREADY );

    SC_METHOD(thread_o_data_V_data_V_1_data_out);
    sensitive << ( o_data_V_data_V_1_payload_A );
    sensitive << ( o_data_V_data_V_1_payload_B );
    sensitive << ( o_data_V_data_V_1_sel );

    SC_METHOD(thread_o_data_V_data_V_1_load_A);
    sensitive << ( o_data_V_data_V_1_sel_wr );
    sensitive << ( o_data_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_o_data_V_data_V_1_load_B);
    sensitive << ( o_data_V_data_V_1_sel_wr );
    sensitive << ( o_data_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_o_data_V_data_V_1_sel);
    sensitive << ( o_data_V_data_V_1_sel_rd );

    SC_METHOD(thread_o_data_V_data_V_1_state_cmp_full);
    sensitive << ( o_data_V_data_V_1_state );

    SC_METHOD(thread_o_data_V_data_V_1_vld_in);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_predicate_op70_write_state3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_o_data_V_data_V_1_vld_out);
    sensitive << ( o_data_V_data_V_1_state );

    SC_METHOD(thread_o_data_V_last_V_1_ack_in);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_o_data_V_last_V_1_ack_out);
    sensitive << ( o_data_TREADY );

    SC_METHOD(thread_o_data_V_last_V_1_data_out);
    sensitive << ( o_data_V_last_V_1_sel );

    SC_METHOD(thread_o_data_V_last_V_1_sel);
    sensitive << ( o_data_V_last_V_1_sel_rd );

    SC_METHOD(thread_o_data_V_last_V_1_vld_in);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_predicate_op70_write_state3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_o_data_V_last_V_1_vld_out);
    sensitive << ( o_data_V_last_V_1_state );

    SC_METHOD(thread_p_Val2_2_7_fu_433_p2);
    sensitive << ( tmp3_fu_424_p2 );
    sensitive << ( tmp4_cast_fu_430_p1 );

    SC_METHOD(thread_phaseClass_V_read_read_fu_124_p2);
    sensitive << ( phaseClass_V );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_start_V_read_read_fu_118_p2);
    sensitive << ( start_V );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp3_fu_424_p2);
    sensitive << ( corHelper_V );
    sensitive << ( tmp_7_5_cast_fu_420_p1 );

    SC_METHOD(thread_tmp4_cast_fu_430_p1);
    sensitive << ( tmp4_reg_489 );

    SC_METHOD(thread_tmp4_fu_293_p2);
    sensitive << ( tmp_7_6_cast_fu_267_p1 );
    sensitive << ( tmp5_cast_fu_289_p1 );

    SC_METHOD(thread_tmp5_cast_fu_289_p1);
    sensitive << ( tmp5_fu_283_p2 );

    SC_METHOD(thread_tmp5_fu_283_p2);
    sensitive << ( tmp_7_7_cast_fu_279_p1 );
    sensitive << ( tmp_7_4_cast_fu_255_p1 );

    SC_METHOD(thread_tmp_1_fu_456_p2);
    sensitive << ( loadCount_V );

    SC_METHOD(thread_tmp_2_fu_307_p4);
    sensitive << ( i_data_TDATA );

    SC_METHOD(thread_tmp_4_fu_445_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( corState_load_reg_476 );
    sensitive << ( cond_reg_485 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( p_Val2_2_7_fu_433_p2 );

    SC_METHOD(thread_tmp_7_4_cast_fu_255_p1);
    sensitive << ( tmp_7_4_fu_247_p3 );

    SC_METHOD(thread_tmp_7_4_fu_247_p3);
    sensitive << ( phaseClass0_V_3 );

    SC_METHOD(thread_tmp_7_5_cast_fu_420_p1);
    sensitive << ( tmp_7_5_fu_413_p3 );

    SC_METHOD(thread_tmp_7_5_fu_413_p3);
    sensitive << ( phaseClass0_V_2_load_reg_480 );

    SC_METHOD(thread_tmp_7_6_cast_fu_267_p1);
    sensitive << ( tmp_7_6_fu_259_p3 );

    SC_METHOD(thread_tmp_7_6_fu_259_p3);
    sensitive << ( phaseClass0_V_1 );

    SC_METHOD(thread_tmp_7_7_cast_fu_279_p1);
    sensitive << ( tmp_7_7_fu_271_p3 );

    SC_METHOD(thread_tmp_7_7_fu_271_p3);
    sensitive << ( phaseClass0_V_0 );

    SC_METHOD(thread_tmp_nbreadreq_fu_130_p4);
    sensitive << ( i_data_TVALID );

    SC_METHOD(thread_tmp_s_fu_317_p3);
    sensitive << ( tmp_2_fu_307_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    o_data_V_data_V_1_sel_rd = SC_LOGIC_0;
    o_data_V_data_V_1_sel_wr = SC_LOGIC_0;
    o_data_V_data_V_1_state = "00";
    o_data_V_last_V_1_sel_rd = SC_LOGIC_0;
    o_data_V_last_V_1_state = "00";
    corState = "0";
    phaseClass0_V_3 = "0000000000000000";
    phaseClass0_V_2 = "0000000000000000";
    phaseClass0_V_1 = "0000000000000000";
    phaseClass0_V_0 = "0000000000000000";
    loadCount_V = "00000000000000000000000000000000";
    corHelper_V = "00000000000000000000000000000000";
    currentState = "0";
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "correlator_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, i_data_TDATA, "(port)i_data_TDATA");
    sc_trace(mVcdFile, i_data_TVALID, "(port)i_data_TVALID");
    sc_trace(mVcdFile, i_data_TREADY, "(port)i_data_TREADY");
    sc_trace(mVcdFile, i_data_TLAST, "(port)i_data_TLAST");
    sc_trace(mVcdFile, o_data_TDATA, "(port)o_data_TDATA");
    sc_trace(mVcdFile, o_data_TVALID, "(port)o_data_TVALID");
    sc_trace(mVcdFile, o_data_TREADY, "(port)o_data_TREADY");
    sc_trace(mVcdFile, o_data_TLAST, "(port)o_data_TLAST");
    sc_trace(mVcdFile, phaseClass_V, "(port)phaseClass_V");
    sc_trace(mVcdFile, start_V, "(port)start_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, o_data_V_data_V_1_data_out, "o_data_V_data_V_1_data_out");
    sc_trace(mVcdFile, o_data_V_data_V_1_vld_in, "o_data_V_data_V_1_vld_in");
    sc_trace(mVcdFile, o_data_V_data_V_1_vld_out, "o_data_V_data_V_1_vld_out");
    sc_trace(mVcdFile, o_data_V_data_V_1_ack_in, "o_data_V_data_V_1_ack_in");
    sc_trace(mVcdFile, o_data_V_data_V_1_ack_out, "o_data_V_data_V_1_ack_out");
    sc_trace(mVcdFile, o_data_V_data_V_1_payload_A, "o_data_V_data_V_1_payload_A");
    sc_trace(mVcdFile, o_data_V_data_V_1_payload_B, "o_data_V_data_V_1_payload_B");
    sc_trace(mVcdFile, o_data_V_data_V_1_sel_rd, "o_data_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, o_data_V_data_V_1_sel_wr, "o_data_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, o_data_V_data_V_1_sel, "o_data_V_data_V_1_sel");
    sc_trace(mVcdFile, o_data_V_data_V_1_load_A, "o_data_V_data_V_1_load_A");
    sc_trace(mVcdFile, o_data_V_data_V_1_load_B, "o_data_V_data_V_1_load_B");
    sc_trace(mVcdFile, o_data_V_data_V_1_state, "o_data_V_data_V_1_state");
    sc_trace(mVcdFile, o_data_V_data_V_1_state_cmp_full, "o_data_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, o_data_V_last_V_1_data_out, "o_data_V_last_V_1_data_out");
    sc_trace(mVcdFile, o_data_V_last_V_1_vld_in, "o_data_V_last_V_1_vld_in");
    sc_trace(mVcdFile, o_data_V_last_V_1_vld_out, "o_data_V_last_V_1_vld_out");
    sc_trace(mVcdFile, o_data_V_last_V_1_ack_in, "o_data_V_last_V_1_ack_in");
    sc_trace(mVcdFile, o_data_V_last_V_1_ack_out, "o_data_V_last_V_1_ack_out");
    sc_trace(mVcdFile, o_data_V_last_V_1_sel_rd, "o_data_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, o_data_V_last_V_1_sel, "o_data_V_last_V_1_sel");
    sc_trace(mVcdFile, o_data_V_last_V_1_state, "o_data_V_last_V_1_state");
    sc_trace(mVcdFile, corState, "corState");
    sc_trace(mVcdFile, phaseClass0_V_3, "phaseClass0_V_3");
    sc_trace(mVcdFile, phaseClass0_V_2, "phaseClass0_V_2");
    sc_trace(mVcdFile, phaseClass0_V_1, "phaseClass0_V_1");
    sc_trace(mVcdFile, phaseClass0_V_0, "phaseClass0_V_0");
    sc_trace(mVcdFile, loadCount_V, "loadCount_V");
    sc_trace(mVcdFile, corHelper_V, "corHelper_V");
    sc_trace(mVcdFile, currentState, "currentState");
    sc_trace(mVcdFile, i_data_TDATA_blk_n, "i_data_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, currentState_load_load_fu_299_p1, "currentState_load_load_fu_299_p1");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_130_p4, "tmp_nbreadreq_fu_130_p4");
    sc_trace(mVcdFile, o_data_TDATA_blk_n, "o_data_TDATA_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, corState_load_reg_476, "corState_load_reg_476");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_corState_load_reg_476, "ap_reg_pp0_iter1_corState_load_reg_476");
    sc_trace(mVcdFile, cond_reg_485, "cond_reg_485");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_cond_reg_485, "ap_reg_pp0_iter1_cond_reg_485");
    sc_trace(mVcdFile, tmp_4_reg_502, "tmp_4_reg_502");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_corState_load_reg_476, "ap_reg_pp0_iter2_corState_load_reg_476");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_cond_reg_485, "ap_reg_pp0_iter2_cond_reg_485");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_4_reg_502, "ap_reg_pp0_iter2_tmp_4_reg_502");
    sc_trace(mVcdFile, ap_predicate_op33_read_state1, "ap_predicate_op33_read_state1");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_predicate_op70_write_state3, "ap_predicate_op70_write_state3");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_predicate_op93_write_state4, "ap_predicate_op93_write_state4");
    sc_trace(mVcdFile, ap_block_state4_io, "ap_block_state4_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, start_V_read_read_fu_118_p2, "start_V_read_read_fu_118_p2");
    sc_trace(mVcdFile, phaseClass_V_read_read_fu_124_p2, "phaseClass_V_read_read_fu_124_p2");
    sc_trace(mVcdFile, corState_load_load_fu_221_p1, "corState_load_load_fu_221_p1");
    sc_trace(mVcdFile, phaseClass0_V_2_load_reg_480, "phaseClass0_V_2_load_reg_480");
    sc_trace(mVcdFile, cond_fu_241_p2, "cond_fu_241_p2");
    sc_trace(mVcdFile, tmp4_fu_293_p2, "tmp4_fu_293_p2");
    sc_trace(mVcdFile, tmp4_reg_489, "tmp4_reg_489");
    sc_trace(mVcdFile, currentState_load_reg_494, "currentState_load_reg_494");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_currentState_load_reg_494, "ap_reg_pp0_iter1_currentState_load_reg_494");
    sc_trace(mVcdFile, tmp_reg_498, "tmp_reg_498");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_reg_498, "ap_reg_pp0_iter1_tmp_reg_498");
    sc_trace(mVcdFile, tmp_4_fu_445_p2, "tmp_4_fu_445_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_phi_mux_corState_flag_phi_fu_162_p4, "ap_phi_mux_corState_flag_phi_fu_162_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_corState_flag_reg_159, "ap_phi_reg_pp0_iter0_corState_flag_reg_159");
    sc_trace(mVcdFile, ap_phi_mux_corState_flag_1_phi_fu_173_p4, "ap_phi_mux_corState_flag_1_phi_fu_173_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_corState_flag_1_reg_170, "ap_phi_reg_pp0_iter0_corState_flag_1_reg_170");
    sc_trace(mVcdFile, ap_phi_mux_corState_new_1_phi_fu_184_p4, "ap_phi_mux_corState_new_1_phi_fu_184_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_corState_new_1_reg_181, "ap_phi_reg_pp0_iter0_corState_new_1_reg_181");
    sc_trace(mVcdFile, ap_phi_mux_corState_flag_2_phi_fu_195_p4, "ap_phi_mux_corState_flag_2_phi_fu_195_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_corState_flag_2_reg_192, "ap_phi_reg_pp0_iter0_corState_flag_2_reg_192");
    sc_trace(mVcdFile, ap_phi_mux_corState_new_2_phi_fu_207_p4, "ap_phi_mux_corState_new_2_phi_fu_207_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_corState_new_2_reg_204, "ap_phi_reg_pp0_iter0_corState_new_2_reg_204");
    sc_trace(mVcdFile, tmp_s_fu_317_p3, "tmp_s_fu_317_p3");
    sc_trace(mVcdFile, tmp_1_fu_456_p2, "tmp_1_fu_456_p2");
    sc_trace(mVcdFile, p_Val2_2_7_fu_433_p2, "p_Val2_2_7_fu_433_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_7_4_fu_247_p3, "tmp_7_4_fu_247_p3");
    sc_trace(mVcdFile, tmp_7_6_fu_259_p3, "tmp_7_6_fu_259_p3");
    sc_trace(mVcdFile, tmp_7_7_fu_271_p3, "tmp_7_7_fu_271_p3");
    sc_trace(mVcdFile, tmp_7_7_cast_fu_279_p1, "tmp_7_7_cast_fu_279_p1");
    sc_trace(mVcdFile, tmp_7_4_cast_fu_255_p1, "tmp_7_4_cast_fu_255_p1");
    sc_trace(mVcdFile, tmp5_fu_283_p2, "tmp5_fu_283_p2");
    sc_trace(mVcdFile, tmp_7_6_cast_fu_267_p1, "tmp_7_6_cast_fu_267_p1");
    sc_trace(mVcdFile, tmp5_cast_fu_289_p1, "tmp5_cast_fu_289_p1");
    sc_trace(mVcdFile, tmp_2_fu_307_p4, "tmp_2_fu_307_p4");
    sc_trace(mVcdFile, tmp_7_5_fu_413_p3, "tmp_7_5_fu_413_p3");
    sc_trace(mVcdFile, tmp_7_5_cast_fu_420_p1, "tmp_7_5_cast_fu_420_p1");
    sc_trace(mVcdFile, tmp3_fu_424_p2, "tmp3_fu_424_p2");
    sc_trace(mVcdFile, tmp4_cast_fu_430_p1, "tmp4_cast_fu_430_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_304, "ap_condition_304");
    sc_trace(mVcdFile, ap_condition_162, "ap_condition_162");
#endif

    }
    mHdltvinHandle.open("correlator.hdltvin.dat");
    mHdltvoutHandle.open("correlator.hdltvout.dat");
}

correlator::~correlator() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void correlator::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        corHelper_V = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, corState_load_reg_476.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, cond_reg_485.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
            corHelper_V = p_Val2_2_7_fu_433_p2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        corState = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_corState_flag_2_phi_fu_195_p4.read()))) {
            corState = ap_phi_mux_corState_new_2_phi_fu_207_p4.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        currentState = ap_const_lv1_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, currentState_load_load_fu_299_p1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, start_V_read_read_fu_118_p2.read())))) {
            currentState = ap_const_lv1_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        loadCount_V = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_currentState_load_reg_494.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_tmp_reg_498.read()))) {
            loadCount_V = tmp_1_fu_456_p2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_out.read()))) {
            o_data_V_data_V_1_sel_rd =  (sc_logic) (~o_data_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_in.read()))) {
            o_data_V_data_V_1_sel_wr =  (sc_logic) (~o_data_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            o_data_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            o_data_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(o_data_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_ack_out.read()))))) {
            o_data_V_data_V_1_state = ap_const_lv2_3;
        } else {
            o_data_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_out.read()))) {
            o_data_V_last_V_1_sel_rd =  (sc_logic) (~o_data_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        o_data_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, o_data_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, o_data_V_last_V_1_state.read())))) {
            o_data_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, o_data_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, o_data_V_last_V_1_state.read())))) {
            o_data_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, o_data_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, o_data_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, o_data_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_last_V_1_ack_out.read()))))) {
            o_data_V_last_V_1_state = ap_const_lv2_3;
        } else {
            o_data_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_0 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,4,4>(phaseClass_V_read_read_fu_124_p2.read(), ap_const_lv4_0))) {
            phaseClass0_V_0 = tmp_s_fu_317_p3.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_1 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,4,4>(phaseClass_V_read_read_fu_124_p2.read(), ap_const_lv4_0))) {
            phaseClass0_V_1 = phaseClass0_V_0.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_2 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,4,4>(phaseClass_V_read_read_fu_124_p2.read(), ap_const_lv4_0))) {
            phaseClass0_V_2 = phaseClass0_V_1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        phaseClass0_V_3 = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,4,4>(phaseClass_V_read_read_fu_124_p2.read(), ap_const_lv4_0))) {
            phaseClass0_V_3 = phaseClass0_V_2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_cond_reg_485 = cond_reg_485.read();
        ap_reg_pp0_iter1_corState_load_reg_476 = corState_load_reg_476.read();
        ap_reg_pp0_iter1_currentState_load_reg_494 = currentState_load_reg_494.read();
        ap_reg_pp0_iter1_tmp_reg_498 = tmp_reg_498.read();
        corState_load_reg_476 = corState.read();
        currentState_load_reg_494 = currentState.read();
        phaseClass0_V_2_load_reg_480 = phaseClass0_V_2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        ap_reg_pp0_iter2_cond_reg_485 = ap_reg_pp0_iter1_cond_reg_485.read();
        ap_reg_pp0_iter2_corState_load_reg_476 = ap_reg_pp0_iter1_corState_load_reg_476.read();
        ap_reg_pp0_iter2_tmp_4_reg_502 = tmp_4_reg_502.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, corState_load_load_fu_221_p1.read()))) {
        cond_reg_485 = cond_fu_241_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_load_A.read())) {
        o_data_V_data_V_1_payload_A = loadCount_V.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_load_B.read())) {
        o_data_V_data_V_1_payload_B = loadCount_V.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, corState_load_load_fu_221_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, cond_fu_241_p2.read()))) {
        tmp4_reg_489 = tmp4_fu_293_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, corState_load_reg_476.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, cond_reg_485.read()))) {
        tmp_4_reg_502 = tmp_4_fu_445_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_reg_498 = tmp_nbreadreq_fu_130_p4.read();
    }
}

void correlator::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void correlator::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void correlator::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op33_read_state1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()))));
}

void correlator::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op33_read_state1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read()))));
}

void correlator::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op33_read_state1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read()))));
}

void correlator::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, i_data_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op33_read_state1.read()));
}

void correlator::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void correlator::thread_ap_block_state3_io() {
    ap_block_state3_io = (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_write_state3.read()));
}

void correlator::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void correlator::thread_ap_block_state4_io() {
    ap_block_state4_io = (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op93_write_state4.read()));
}

void correlator::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = (esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, o_data_V_last_V_1_ack_in.read()));
}

void correlator::thread_ap_condition_162() {
    ap_condition_162 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0));
}

void correlator::thread_ap_condition_304() {
    ap_condition_304 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()));
}

void correlator::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void correlator::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void correlator::thread_ap_phi_mux_corState_flag_1_phi_fu_173_p4() {
    if (esl_seteq<1,1,1>(ap_condition_304.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_130_p4.read())) {
            ap_phi_mux_corState_flag_1_phi_fu_173_p4 = ap_phi_mux_corState_flag_phi_fu_162_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read())) {
            ap_phi_mux_corState_flag_1_phi_fu_173_p4 = ap_const_lv1_1;
        } else {
            ap_phi_mux_corState_flag_1_phi_fu_173_p4 = ap_phi_reg_pp0_iter0_corState_flag_1_reg_170.read();
        }
    } else {
        ap_phi_mux_corState_flag_1_phi_fu_173_p4 = ap_phi_reg_pp0_iter0_corState_flag_1_reg_170.read();
    }
}

void correlator::thread_ap_phi_mux_corState_flag_2_phi_fu_195_p4() {
    if (esl_seteq<1,1,1>(ap_condition_162.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, currentState_load_load_fu_299_p1.read())) {
            ap_phi_mux_corState_flag_2_phi_fu_195_p4 = ap_phi_mux_corState_flag_phi_fu_162_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read())) {
            ap_phi_mux_corState_flag_2_phi_fu_195_p4 = ap_phi_mux_corState_flag_1_phi_fu_173_p4.read();
        } else {
            ap_phi_mux_corState_flag_2_phi_fu_195_p4 = ap_phi_reg_pp0_iter0_corState_flag_2_reg_192.read();
        }
    } else {
        ap_phi_mux_corState_flag_2_phi_fu_195_p4 = ap_phi_reg_pp0_iter0_corState_flag_2_reg_192.read();
    }
}

void correlator::thread_ap_phi_mux_corState_flag_phi_fu_162_p4() {
    if (esl_seteq<1,1,1>(ap_condition_162.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, corState_load_load_fu_221_p1.read())) {
            ap_phi_mux_corState_flag_phi_fu_162_p4 = ap_const_lv1_1;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, corState_load_load_fu_221_p1.read())) {
            ap_phi_mux_corState_flag_phi_fu_162_p4 = ap_const_lv1_0;
        } else {
            ap_phi_mux_corState_flag_phi_fu_162_p4 = ap_phi_reg_pp0_iter0_corState_flag_reg_159.read();
        }
    } else {
        ap_phi_mux_corState_flag_phi_fu_162_p4 = ap_phi_reg_pp0_iter0_corState_flag_reg_159.read();
    }
}

void correlator::thread_ap_phi_mux_corState_new_1_phi_fu_184_p4() {
    if (esl_seteq<1,1,1>(ap_condition_304.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_130_p4.read())) {
            ap_phi_mux_corState_new_1_phi_fu_184_p4 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read())) {
            ap_phi_mux_corState_new_1_phi_fu_184_p4 = ap_const_lv1_1;
        } else {
            ap_phi_mux_corState_new_1_phi_fu_184_p4 = ap_phi_reg_pp0_iter0_corState_new_1_reg_181.read();
        }
    } else {
        ap_phi_mux_corState_new_1_phi_fu_184_p4 = ap_phi_reg_pp0_iter0_corState_new_1_reg_181.read();
    }
}

void correlator::thread_ap_phi_mux_corState_new_2_phi_fu_207_p4() {
    if (esl_seteq<1,1,1>(ap_condition_162.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, currentState_load_load_fu_299_p1.read())) {
            ap_phi_mux_corState_new_2_phi_fu_207_p4 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read())) {
            ap_phi_mux_corState_new_2_phi_fu_207_p4 = ap_phi_mux_corState_new_1_phi_fu_184_p4.read();
        } else {
            ap_phi_mux_corState_new_2_phi_fu_207_p4 = ap_phi_reg_pp0_iter0_corState_new_2_reg_204.read();
        }
    } else {
        ap_phi_mux_corState_new_2_phi_fu_207_p4 = ap_phi_reg_pp0_iter0_corState_new_2_reg_204.read();
    }
}

void correlator::thread_ap_phi_reg_pp0_iter0_corState_flag_1_reg_170() {
    ap_phi_reg_pp0_iter0_corState_flag_1_reg_170 = "X";
}

void correlator::thread_ap_phi_reg_pp0_iter0_corState_flag_2_reg_192() {
    ap_phi_reg_pp0_iter0_corState_flag_2_reg_192 = "X";
}

void correlator::thread_ap_phi_reg_pp0_iter0_corState_flag_reg_159() {
    ap_phi_reg_pp0_iter0_corState_flag_reg_159 = "X";
}

void correlator::thread_ap_phi_reg_pp0_iter0_corState_new_1_reg_181() {
    ap_phi_reg_pp0_iter0_corState_new_1_reg_181 = "X";
}

void correlator::thread_ap_phi_reg_pp0_iter0_corState_new_2_reg_204() {
    ap_phi_reg_pp0_iter0_corState_new_2_reg_204 = "X";
}

void correlator::thread_ap_predicate_op33_read_state1() {
    ap_predicate_op33_read_state1 = (esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read()));
}

void correlator::thread_ap_predicate_op70_write_state3() {
    ap_predicate_op70_write_state3 = (esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_corState_load_reg_476.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_cond_reg_485.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_reg_502.read()));
}

void correlator::thread_ap_predicate_op93_write_state4() {
    ap_predicate_op93_write_state4 = (esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter2_corState_load_reg_476.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter2_cond_reg_485.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter2_tmp_4_reg_502.read()));
}

void correlator::thread_ap_reset_idle_pp0() {
    if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void correlator::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void correlator::thread_cond_fu_241_p2() {
    cond_fu_241_p2 = (!phaseClass_V.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(phaseClass_V.read() == ap_const_lv4_0);
}

void correlator::thread_corState_load_load_fu_221_p1() {
    corState_load_load_fu_221_p1 = corState.read();
}

void correlator::thread_currentState_load_load_fu_299_p1() {
    currentState_load_load_fu_299_p1 = currentState.read();
}

void correlator::thread_i_data_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, currentState.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_nbreadreq_fu_130_p4.read()))) {
        i_data_TDATA_blk_n = i_data_TVALID.read();
    } else {
        i_data_TDATA_blk_n = ap_const_logic_1;
    }
}

void correlator::thread_i_data_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op33_read_state1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_data_TREADY = ap_const_logic_1;
    } else {
        i_data_TREADY = ap_const_logic_0;
    }
}

void correlator::thread_o_data_TDATA() {
    o_data_TDATA = o_data_V_data_V_1_data_out.read();
}

void correlator::thread_o_data_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_corState_load_reg_476.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter1_cond_reg_485.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_reg_502.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter2_corState_load_reg_476.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter2_cond_reg_485.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, ap_reg_pp0_iter2_tmp_4_reg_502.read())))) {
        o_data_TDATA_blk_n = o_data_V_data_V_1_state.read()[1];
    } else {
        o_data_TDATA_blk_n = ap_const_logic_1;
    }
}

void correlator::thread_o_data_TLAST() {
    o_data_TLAST = o_data_V_last_V_1_data_out.read();
}

void correlator::thread_o_data_TVALID() {
    o_data_TVALID = o_data_V_last_V_1_state.read()[0];
}

void correlator::thread_o_data_V_data_V_1_ack_in() {
    o_data_V_data_V_1_ack_in = o_data_V_data_V_1_state.read()[1];
}

void correlator::thread_o_data_V_data_V_1_ack_out() {
    o_data_V_data_V_1_ack_out = o_data_TREADY.read();
}

void correlator::thread_o_data_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, o_data_V_data_V_1_sel.read())) {
        o_data_V_data_V_1_data_out = o_data_V_data_V_1_payload_B.read();
    } else {
        o_data_V_data_V_1_data_out = o_data_V_data_V_1_payload_A.read();
    }
}

void correlator::thread_o_data_V_data_V_1_load_A() {
    o_data_V_data_V_1_load_A = (o_data_V_data_V_1_state_cmp_full.read() & ~o_data_V_data_V_1_sel_wr.read());
}

void correlator::thread_o_data_V_data_V_1_load_B() {
    o_data_V_data_V_1_load_B = (o_data_V_data_V_1_sel_wr.read() & o_data_V_data_V_1_state_cmp_full.read());
}

void correlator::thread_o_data_V_data_V_1_sel() {
    o_data_V_data_V_1_sel = o_data_V_data_V_1_sel_rd.read();
}

void correlator::thread_o_data_V_data_V_1_state_cmp_full() {
    o_data_V_data_V_1_state_cmp_full =  (sc_logic) ((!o_data_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(o_data_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void correlator::thread_o_data_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_write_state3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        o_data_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        o_data_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void correlator::thread_o_data_V_data_V_1_vld_out() {
    o_data_V_data_V_1_vld_out = o_data_V_data_V_1_state.read()[0];
}

void correlator::thread_o_data_V_last_V_1_ack_in() {
    o_data_V_last_V_1_ack_in = o_data_V_last_V_1_state.read()[1];
}

void correlator::thread_o_data_V_last_V_1_ack_out() {
    o_data_V_last_V_1_ack_out = o_data_TREADY.read();
}

void correlator::thread_o_data_V_last_V_1_data_out() {
    o_data_V_last_V_1_data_out = ap_const_lv1_0;
}

void correlator::thread_o_data_V_last_V_1_sel() {
    o_data_V_last_V_1_sel = o_data_V_last_V_1_sel_rd.read();
}

void correlator::thread_o_data_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_write_state3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        o_data_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        o_data_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void correlator::thread_o_data_V_last_V_1_vld_out() {
    o_data_V_last_V_1_vld_out = o_data_V_last_V_1_state.read()[0];
}

void correlator::thread_p_Val2_2_7_fu_433_p2() {
    p_Val2_2_7_fu_433_p2 = (!tmp3_fu_424_p2.read().is_01() || !tmp4_cast_fu_430_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp3_fu_424_p2.read()) + sc_bigint<32>(tmp4_cast_fu_430_p1.read()));
}

void correlator::thread_phaseClass_V_read_read_fu_124_p2() {
    phaseClass_V_read_read_fu_124_p2 = phaseClass_V.read();
}

void correlator::thread_start_V_read_read_fu_118_p2() {
    start_V_read_read_fu_118_p2 = start_V.read();
}

void correlator::thread_tmp3_fu_424_p2() {
    tmp3_fu_424_p2 = (!tmp_7_5_cast_fu_420_p1.read().is_01() || !corHelper_V.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_7_5_cast_fu_420_p1.read()) + sc_biguint<32>(corHelper_V.read()));
}

void correlator::thread_tmp4_cast_fu_430_p1() {
    tmp4_cast_fu_430_p1 = esl_sext<32,23>(tmp4_reg_489.read());
}

void correlator::thread_tmp4_fu_293_p2() {
    tmp4_fu_293_p2 = (!tmp_7_6_cast_fu_267_p1.read().is_01() || !tmp5_cast_fu_289_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(tmp_7_6_cast_fu_267_p1.read()) + sc_bigint<23>(tmp5_cast_fu_289_p1.read()));
}

void correlator::thread_tmp5_cast_fu_289_p1() {
    tmp5_cast_fu_289_p1 = esl_sext<23,22>(tmp5_fu_283_p2.read());
}

void correlator::thread_tmp5_fu_283_p2() {
    tmp5_fu_283_p2 = (!tmp_7_7_cast_fu_279_p1.read().is_01() || !tmp_7_4_cast_fu_255_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(tmp_7_7_cast_fu_279_p1.read()) + sc_bigint<22>(tmp_7_4_cast_fu_255_p1.read()));
}

void correlator::thread_tmp_1_fu_456_p2() {
    tmp_1_fu_456_p2 = (!loadCount_V.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(loadCount_V.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void correlator::thread_tmp_2_fu_307_p4() {
    tmp_2_fu_307_p4 = i_data_TDATA.read().range(26, 16);
}

void correlator::thread_tmp_4_fu_445_p2() {
    tmp_4_fu_445_p2 = (!p_Val2_2_7_fu_433_p2.read().is_01() || !ap_const_lv32_1000.is_01())? sc_lv<1>(): (sc_bigint<32>(p_Val2_2_7_fu_433_p2.read()) > sc_bigint<32>(ap_const_lv32_1000));
}

void correlator::thread_tmp_7_4_cast_fu_255_p1() {
    tmp_7_4_cast_fu_255_p1 = esl_sext<22,21>(tmp_7_4_fu_247_p3.read());
}

void correlator::thread_tmp_7_4_fu_247_p3() {
    tmp_7_4_fu_247_p3 = esl_concat<16,5>(phaseClass0_V_3.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_7_5_cast_fu_420_p1() {
    tmp_7_5_cast_fu_420_p1 = esl_sext<32,21>(tmp_7_5_fu_413_p3.read());
}

void correlator::thread_tmp_7_5_fu_413_p3() {
    tmp_7_5_fu_413_p3 = esl_concat<16,5>(phaseClass0_V_2_load_reg_480.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_7_6_cast_fu_267_p1() {
    tmp_7_6_cast_fu_267_p1 = esl_sext<23,21>(tmp_7_6_fu_259_p3.read());
}

void correlator::thread_tmp_7_6_fu_259_p3() {
    tmp_7_6_fu_259_p3 = esl_concat<16,5>(phaseClass0_V_1.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_7_7_cast_fu_279_p1() {
    tmp_7_7_cast_fu_279_p1 = esl_sext<22,21>(tmp_7_7_fu_271_p3.read());
}

void correlator::thread_tmp_7_7_fu_271_p3() {
    tmp_7_7_fu_271_p3 = esl_concat<16,5>(phaseClass0_V_0.read(), ap_const_lv5_0);
}

void correlator::thread_tmp_nbreadreq_fu_130_p4() {
    tmp_nbreadreq_fu_130_p4 =  (sc_lv<1>) ((i_data_TVALID.read()));
}

void correlator::thread_tmp_s_fu_317_p3() {
    tmp_s_fu_317_p3 = esl_concat<11,5>(tmp_2_fu_307_p4.read(), ap_const_lv5_0);
}

void correlator::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void correlator::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i_data_TDATA\" :  \"" << i_data_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i_data_TVALID\" :  \"" << i_data_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"i_data_TREADY\" :  \"" << i_data_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"i_data_TLAST\" :  \"" << i_data_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"o_data_TDATA\" :  \"" << o_data_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"o_data_TVALID\" :  \"" << o_data_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"o_data_TREADY\" :  \"" << o_data_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"o_data_TLAST\" :  \"" << o_data_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"phaseClass_V\" :  \"" << phaseClass_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"start_V\" :  \"" << start_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

